In [1]:
import pandas as pd
from dotenv import dotenv_values
import requests
from io import BytesIO

In [12]:
#Mostrar todas la columnas de los DataFrame
pd.set_option("display.max_columns", None)  # mostrar todas las columnas

In [4]:
config = dotenv_values(dotenv_path=".env")

In [5]:
url = "https://raw.githubusercontent.com/Nicolasg2c/dc_model_ts/main/common/data/datos_deterioro_cognitivo.xlsx"

headers = {"Authorization": f"Bearer {config['GITHUB_TOKEN']}"}
r = requests.get(url, headers=headers, timeout=30)
r.raise_for_status()  # Check if the request was successful

xlsx_data = pd.read_excel(BytesIO(r.content), header=None, sheet_name=None, engine="openpyxl")

In [114]:
##Mapeo de las columnas a buscar en cada hoja
features = [
    'orientacion_en_persona',
    'orientacion_en_espacio',
    'orientacion_en_tiempo',

    'atencion_sostenida_auditiva',
    'atencion_sostenida_visual',
    'atencion_selectiva_visual',
    'atencion_dividida_visual',

    'denominacion_de_imagenes',
    'comprension_de_ordenes',
    'material_verbal_complejo',

    'evocacion_inmediata_lista_a',
    'recuerdo_inmediato_lista_a',
    'recuerdo_inmediato_lista_b',
    'recuerdo_libre_a_corto_plazo',
    'recuerdo_libre_a_largo_plazo',
    'recuerdo_libre_a_largo_plazo_clave',
    'reconocimiento',

    'evocacion_diferida',
    'reconocimiento_inmediato_ensayo_2',
    'reconocimiento_diferido_ensayo_3',

    'imagenes_superpuesta',

    'constructiva',
    'ideomotora_gestos_simbolicos_a_la_orden_derecha',
    'ideomotora_gestos_simbolicos_a_la_orden_izquierda',
    'ideomotora_gestos_simbolicos_a_la_imitacion_derecha',
    'ideomotora_gestos_simbolicos_a_la_imitacion_izquierda',

    'memoria_de_trabajo_digitos_inversos',
    'memoria_de_trabajo_digitos_secuenciales',
    'test_de_fluidez_fonologica_fas_f',
    'test_de_fluidez_fonologica_fas_a',
    'test_de_fluidez_fonologica_fas_s',
    'evocacion_categorial_semantica',
    'semejanzas',
    'matrices',
    'comprension_abstraccion',
    'atencion_alternante',
    'stroop_a',
    'stroop_b',
    'stroop_c',
    'stroop_palabra',
    'stroop_colores',
    'stroop_interferencia',
  ]

In [7]:
cleaned_sheets = {}
for name, sheet in xlsx_data.items():
    sheet = sheet.dropna(how="all")       # eliminar filas vacías
    # sheet.columns = sheet.iloc[0]         # primera fila como headers
    # sheet = sheet.drop(sheet.index[0])    # eliminar fila usada como header
    sheet = sheet.reset_index(drop=True)
    cleaned_sheets[name] = sheet

In [53]:
print(f'Cantidad de datos {len(cleaned_sheets)} \n')
print(f'Nombre de las hojas procesadas:\n ')
for name, sheet in cleaned_sheets.items():
    print(f'{name}')

Cantidad de datos 125

Nombre de las hojas procesadas:

S1-F067-58
GC1-60
GC2-62
F021-72
S2-F067-53
GC3-60
S3-F067-66
GC4-72
GC5-62
S4-F067-66
GC6-69
GC7-70
F022-71
GC8-79
S5-F067-73
F023-87
F024-72
S6-F067-65
F025-82
GC8-80
GC9-66
GC10-65
F026-92
S7-F067-76
S8-F067-75
F027-79
CG11-72
S9-F067-66
S10-F067-65
GC12-65
S11-F067-84
F028-70
s12-f067-77
S13-F067-77
F029-62
S14-F067-69
F0210-77
F0211-79
S15-F067-74
F0212-65
GC13-74
S16-F067-60
GC14-67
F0213-85
S17-F067-76
S18-F067-72
F0214-73
S19-F064-74
S20-F067-57
S21-F067-68
S22-F067-86
GC15-64
S23-F067-66
S24-F067-96
GC16-76
F0215-73
S25-F067-80
F0216-83
F0217-88
F0218-77
S26-F067-81
S27-F067-66
S28-F067-65
S29-F067-82
F0219-74
S30-F067-87
S31-F067-83
S32-F067-60
S33-F067-57
F0220-77
F0221-57
S34-F067-71
F0222-64
S35-F067-67
GC17-60
S36-F067-51
F0223-73
GC18-52
S37-F067-81
F0224-81
F0225-84
S38-F067-74
S39-F067-74
S40-F067-78
S41-F067-76
GC19-53
F0226-70
F0227-78
S42-F067-68
S43-F067-80
S44-F067-69
F0228-86
S45-F067-57
GC20-59
S46-F067-66
GC21-64
S47-F067-64
S48-F067-61
S49-F067-60
GC22-53
GC23-61
GC24-52
S50-F067-55
GC25-61
S51-F067-73
S52-F067-78
S53-F067-54
S54-F067-68
S55-F067-64
GC26-59
F0229-71
F0230-67
S56-F067-73
S57-F067-55
GC27-55
GC28-59
F0231-71
F0232-81
S58-F067-65
S59-F067-84
S60-F067-72
S61-F067-75
F0233-85
GC29-65
F0234-87

In [9]:
print('Formato de tabla 1:')
cleaned_sheets['S1-F067-58']

Formato de tabla 1:

,0,1,2,3,4,5,6,7,8,9,10,11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alto: 14 a 19 puntos,NaN,Alto: 80 a 95 puntos
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Promedio: 7 a13 puntos,NaN,Promedio: 30 a 70 puntos
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alteración leve- moderado: 4 a 6 puntos,NaN,Bajo: 10 a 20 puntos
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alteración severa: 1 a 3 puntos,NaN,Déficit: <5 puntos
4,Dominio-Neuropsi Atención y Memoria- Test de B...,NaN,Puntuación obtenida,Puntuación normalizada,Interpretación,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Orientación,Tiempo,2/4 p,1,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Espacio,1/2 p,1,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Persona,1/1 p,11,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Atención y concentración,Dígitos en progresión,3/9 p,3,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Detección visual total *2 comisiones*,9,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Series sucesivas,2/3 p,10,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Memoria - Codificación,Curva de Memoria Volumen Promedio,5/12 p,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Memoria Verbal Espontánea total,4/12 p,9,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,Memoria Verbal Claves Total,2/12 p,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Memoria Verbal Reconocimiento *1 fr*,8/12 p,11,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,Memoria Lógica Promedio Historias,6/16 p,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Memoria Lógica Promedio Historias,5/16 p,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Memoria visual,Caras codificación,4/4 p,11,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,Reconocimiento Caras,2/2 p,11,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,Evocación figura semicompleja,15/36 p,10,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Gnosias,Figuras sobrepuestas (TB),20/20 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Lenguaje,Semejanzas (TB),8/12 p,60,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,Denominación (TB),14/14 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,Lectura de palabras (TB),6/6 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,Material verbal complejo (TB),9/9 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,Comprensión ejecución de ordenes (TB),13/16 p,5,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Praxias,Copia de figura compleja,32/36 p,12,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Gestos simbólicos (TB),10/10 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,Imitación de posturas (TB),8/8 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,"Funciones ejecutivas, conceptuales y motoras",Formación categorías,7/25 p,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,Fluidez verbal semántica,12,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,Fluidez verbal fonológica,6,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,Fluidez no verbal,5,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,Comprensión abstractacta-refranes (TB),10/10 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,Semejanzas (TB),8/12 p,60,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,Retención dígitos regresión,2/8 p,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,Cubos Regresión,2/9 p,5,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,[1]Perfil general de ejecución. Rango de edad:...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
print('Formato de tabla 2:')
cleaned_sheets['GC4-72']

Formato de tabla 2:

,0,1,2,3
0,FUNCIÓN EVALUADA (TEST EMPLEADO),P. Directa,Percentil o P. Directa,Clasificación
1,Orientación,NaN,NaN,NaN
2,Orientación en persona (TB),7 de 7,95,Alto
3,Orientación en espacio (TB),5 de 5,95,Alto
4,Orientación en tiempo (TB),20 de 23,5,Bajo
5,Capacidad atencional y velocidad de procesamiento,NaN,NaN,NaN
6,Atención sostenida auditiva (Dígitos directos ...,6/16 p,8,Promedio
7,Atención sostenida visual (TMT-A),32 sg,95,Alto
8,Atención selectiva visual (Búsqueda de símbolos),29,13,Promedio
9,Atención dividida visual (Clave de números-WAIS),42,11,Promedio
10,Lenguaje,NaN,NaN,NaN
11,Denominación de imágenes (TB),14/14 p,95,Alto
12,Comprensión de órdenes (TB),16/16 p,95,Alto
13,Material Verbal Complejo (TB),9 de 9,95,Alto
14,Memoria Verbal Test de Aprendizaje de Rey,NaN,NaN,NaN
15,Evocación inmediata Lista A ensayo 1,3/16 p,3/16 p,Promedio
16,Recuerdo inmediato Lista A ensayo 5,7/16 p,7/16 p,Bajo
17,Recuerdo inmediato Lista B,2/16 p,2/16 p,Bajo
18,Recuerdo libre a corto plazo,6/16 p,6/16 p,Bajo
19,Recuerdo libre a largo plazo,6/16 p,6/16 p,Bajo
20,Reconocimiento,12/16 p,12/16 p,Promedio
21,Memoria visual,NaN,NaN,NaN
22,Evocación diferida (Figura compleja de Rey),30/36 p,95,Alto
23,Capacidad Visuoperceptiva,NaN,NaN,NaN
24,Matrices (WAIS-IV),12/26 p,11,Promedio
25,Imágenes superpuestas (TB),20/20,95,Alto
26,Praxis,NaN,NaN,NaN
27,Constructiva (Figura compleja de Rey),36/36 p,85,Alto
28,Ideomotora Gestos simbólicos a la imitación -d...,10 de 10,95,Alto
29,Ideomotora Gestos simbólicos a la imitación -i...,10 de 10,95,Alto
30,Funciones ejecutivas,NaN,NaN,NaN
31,Memoria de Trabajo (Dígitos inversos WAIS-IV),6/16 p,10,Promedio
32,Memoria de Trabajo (Dígitos secuenciales WAIS-IV),7/16 p,10,Promedio
33,Test de fluidez fonológica FAS F,7,25,Promedio
34,Test de fluidez fonológica FAS A,11,55,Promedio
35,Test de fluidez fonológica FAS S,7,25,Promedio
36,Stroop Palabra,73,30,Promedio
37,Stroop Color,55,45,Promedio
38,Stroop Interferencia,25,30,Promedio
39,Semejanzas (TB),7/10 p,60,Promedio
40,Comprensión -abstracción (TB),12/12 p,95,Alto
41,Matrices (WAIS-IV),12/26 p,11,Promedio
42,Atención alternante (TMT B),120 sg.,65,Promedio

In [11]:
#Funcion para limpiar los nombres de las columnas y dejarlas mas estandarizadas
def clean_value(cadena):
  #Se eliminan espacios, se pasan a minusculas, se reemplazan espacios por guiones bajos, se eliminan acentos y caracteres especiales
  cadena = cadena.strip().lower().replace(' ', '_').replace('-','').replace("á", "a").replace("é", "e").replace("í", "i").replace("ó", "o").replace("ú", "u").replace(".","").replace("(","").replace(")","")
  return cadena

In [ ]:
#Se iteran todas las hojas del archivo
type_of_table = {}
for name, sheet in cleaned_sheets.items():
    #Se define una palabra clave para determinar si el formato es tipo tabla 1 o tabla 2
    key_word = 'espacio'
    #Si la palabra clave existe en la primera columna de los datos, se asume que el formato es tipo tabla 1, si existe en la segunda columna se asume que es tipo tabla 2, si no se encuentra en ninguna de las dos columnas se asume que el formato no se pudo determinar
    time_founded_1 = cleaned_sheets[name].iloc[:, 1].apply(lambda x: key_word in clean_value(str(x)))
    time_founded_0 = cleaned_sheets[name].iloc[:, 0].apply(lambda x: key_word in clean_value(str(x)))
    if(time_founded_1.any()):
        tipo_tabla = 1
    elif(time_founded_0.any()):
        tipo_tabla = 2
    else:
        tipo_tabla = 'no determinada'
        
    type_of_table[name] = tipo_tabla

In [85]:
print(f'Cantidad de datos tipo tabla 1: {list(type_of_table.values()).count(1)}')
print(f'Cantidad de datos tipo tabla 2: {list(type_of_table.values()).count(2)}')
print(f'Cantidad de datos con formato no determinado: {list(type_of_table.values()).count("no determinada")}')

Cantidad de datos tipo tabla 1: 81
Cantidad de datos tipo tabla 2: 36
Cantidad de datos con formato no determinado: 8

In [ ]:
def search_values_test(dataset_raw, dataset_clean):
  df_raw = clean_keys(df_raw)
  patient_data = {}
  for column in df_clean:
    # print(f'buscando el valor de la columna {column}')
    column_keys = df_raw[df_raw.columns[0]]
    column_keys_clean = column_keys.apply(clean_value)
    filter = column_keys_clean.str.contains(column, case=False,na=False)
    if(len(df_raw[filter].index) > 0):
      idx = df_raw[filter].index[0]
      finding_values = df_raw.iloc[idx, df_raw.columns.get_loc("percentil_o_p_directa")]
      # print(f'valor: {finding_values}')
      patient_data[column] = finding_values
    else:
      patient_data[column] = None
  return patient_data

In [191]:
def search_values(data, features):
    #Se crea el dataset que va a contener los datos encontrados en cada hoja.
    dataset = pd.DataFrame()
    #Se separan los datos por formato de tabla para facilitar la busqueda de los valores
    data_table_1 = {name: sheet for name, sheet in cleaned_sheets.items() if type_of_table[name] == 1}
    data_table_2 = {name: sheet for name, sheet in cleaned_sheets.items() if type_of_table[name] == 2}
    
    dataset_1 = pd.concat(data_table_1.values(), ignore_index=False)
    dataset_2 = pd.concat(data_table_2.values(), ignore_index=False)
    
    # Se itera por cada feature a buscar
    for feature in features:
        headers = dataset_1[dataset_1.columns[1]]
        
        print(headers)
        
    # # for idx, (name, sheet) in enumerate(cleaned_sheets.items()):
    # #     if(type_of_table[name] == 1):
    # #         column_keys = data[name].iloc[:, 1]
    # #         #eliminar las filas que no tienen datos en la primera columna
    # #         column_keys = column_keys.dropna()
    # #         print(column_keys)
    # #         print(data)
    # #         # key_cleaned = column_keys.apply(clean_value)
    # #         # print(key_cleaned)

In [192]:
search_values(cleaned_sheets, features)

0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN
                 ...
26       Fluidez verbal semántica
27      Fluidez verbal fonológica
28             Fluidez no verbal
29    Retención dígitos regresión
30                            NaN
Name: 1, Length: 3008, dtype: object