In [1]:
import pandas as pd
from dotenv import dotenv_values
import requests
from io import BytesIO

In [2]:
#Mostrar todas la columnas de los DataFrame
pd.set_option("display.max_columns", None)  # mostrar todas las columnas

In [3]:
config = dotenv_values(dotenv_path=".env")

In [4]:
url = "https://raw.githubusercontent.com/Nicolasg2c/dc_model_ts/main/common/data/datos_deterioro_cognitivo.xlsx"

headers = {"Authorization": f"Bearer {config['GITHUB_TOKEN']}"}
r = requests.get(url, headers=headers, timeout=30)
r.raise_for_status()  # Check if the request was successful

xlsx_data = pd.read_excel(BytesIO(r.content), header=None, sheet_name=None, engine="openpyxl")

In [ ]:
##Mapeo de las columnas a buscar en cada hoja
features = [
    
   #Tabla 0 nivel de estudio: Escolaridad baja
   #Tabla 1 nivel de estudio: Escolaridad alta
    
  #####Orientación
  
  #tabla 0 y tabla 1 con estos nombre ambos quedan en la misma columna
  'tiempo',
  'persona',
  'espacio', 
  
  #####Capacidad atencional

  #tabla 0
  'atencion_sostenida_auditiva', #='digitos_en_progresion',
  'atencion_sostenida_visual', #no tiene equivalencia
  'atencion_selectiva_visual', #no tiene equivalencia
  'atencion_dividida_visual', #Deteccion visual
  #tabla 1
  'digitos_en_progresion',
  'cubos_progresion',
  'deteccion_visual',
  'deteccion_digitos_total',
  'series_sucesivas'

  #####Lenguaje
  
  #tabla 0
  'denominacion',
  'comprension_de_ordenes', #Es posible que no sea crucial
  'material_verbal_complejo', #Es posible que no sea crucial
  # #tabla 1
  # 'denominacion'
  #Semenjanzas puede estar en funciones ejecutivas o lenguaje
  'semejanzas',
  'lectura_de_palabras', # es posible que aparezca igual en ambas tablas
  # 'material_verbal_complejo',
  'comprension_ejecicion_de_ordenes',

  #####California verbal learning test | aprendizaje verbal del rey | memoria verbal
  
  #verbal del rey 
  
  #Tabla 0 - california verbal learning test
  'evocacion_inmediata_lista_a',
  'recuerdo_inmediato_lista_a',
  'recuerdo_inmediato_lista_b',
  'recuerdo_libre_a_corto_plazo',
  'recuerdo_libre_a_largo_plazo',
  'recuerdo_libre_a_largo_plazo_clave',
  'reconocimiento',
  #tabla 0 - aprendizaje verbal del rey
  'evocacion_inmediata_lista_a',
  'evocacion_inmediata_lista_b',
  'recuerdo_inmediato_lista_b',
  'recuerdo_libre_a_corto_plazo',
  'recuerdo_libre_a_largo_plazo',
  'reconocimiento',
  #Tabla 1 #No tiene equivalencia con los otros test de la tabla 0
  'curva_de_memoria_volumen_promedio', 
  'memoria_verbal_espontanea_total',
  'memoria_verbal_claves_total',
  'memoria_verbal_reconocimiento_total',
  'memoria_lógica_promedio_historias',
  'memoria_lógica_promedio_historias',

  #####Memoria visual
  
  #Tabla 0
  'evocacion_diferida',#evocacion_figura_semicompleja
  #Tabla 1
  'caras_codificación',
  'reconocimiento_caras',
  'evocacion_figura_semicompleja',

  #####Genosias | capacidad visuoperceptiva
  
  #tabla 0 y tabla 1
  'imagenes_superpuesta',

  #####Praxis | praxias
  
  #Tabla 0
  'constructiva', #copia_de_figura_compleja
  'ideomotora_gestos_simbolicos_a_la_orden_derecha',
  'ideomotora_gestos_simbolicos_a_la_orden_izquierda',
  'ideomotora_gestos_simbolicos_a_la_imitacion_derecha',
  'ideomotora_gestos_simbolicos_a_la_imitacion_izquierda',
  #Tabla 1
  'copia_de_figura_compleja',
  'gestos_simbolicos',
  'imitacion_de_posturas',

  #####Funciones ejecutivas
  
  #Tabla 0
  'memoria_de_trabajo_digitos_inversos', #retencion_digitos_regresion
  'memoria_de_trabajo_digitos_secuenciales', #no tiene equivalencia
  'test_de_fluidez_fonologica_fas_f',
  'test_de_fluidez_fonologica_fas_a',
  'test_de_fluidez_fonologica_fas_s',
  'evocacion_categorial_semantica',
  'semejanzas',
  'matrices',
  'comprension_abstraccion', #comprension_abstraccion
  'atencion_alternante',
  'stroop_a',
  'stroop_b',
  'stroop_c',
  'stroop_palabra',
  'stroop_colores',
  'stroop_interferencia', #stroop_interferencia
  #tabla 1
  'semejanzas',
  'fluidez_verbal_semantica',
  'fluidez_verbal_fonologica',
  'fluidez_no_verbal',
  'retencion_digitos_regresion',
  ]

In [6]:
cleaned_sheets = {}
for name, sheet in xlsx_data.items():
    sheet = sheet.dropna(how="all")       # eliminar filas vacías
    sheet = sheet.reset_index(drop=True)
    cleaned_sheets[name] = sheet

In [7]:
print(f'Cantidad de datos {len(cleaned_sheets)} \n')
print(f'Nombre de las hojas procesadas:\n ')
for name, sheet in cleaned_sheets.items():
    print(f'{name}')

Cantidad de datos 125

Nombre de las hojas procesadas:

S1-F067-58
GC1-60
GC2-62
F021-72
S2-F067-53
GC3-60
S3-F067-66
GC4-72
GC5-62
S4-F067-66
GC6-69
GC7-70
F022-71
GC8-79
S5-F067-73
F023-87
F024-72
S6-F067-65
F025-82
GC8-80
GC9-66
GC10-65
F026-92
S7-F067-76
S8-F067-75
F027-79
GC11-72
S9-F067-66
S10-F067-65
GC12-65
S11-F067-84
F028-70
s12-f067-77
S13-F067-77
F029-62
S14-F067-69
F0210-77
F0211-79
S15-F067-74
F0212-65
GC13-74
S16-F067-60
GC14-67
F0213-85
S17-F067-76
S18-F067-72
F0214-73
S19-F064-74
S20-F067-57
S21-F067-68
S22-F067-86
GC15-64
S23-F067-66
S24-F067-96
GC16-76
F0215-73
S25-F067-80
F0216-83
F0217-88
F0218-77
S26-F067-81
S27-F067-66
S28-F067-65
S29-F067-82
F0219-74
S30-F067-87
S31-F067-83
S32-F067-60
S33-F067-57
F0220-77
F0221-57
S34-F067-71
F0222-64
S35-F067-67
GC17-60
S36-F067-51
F0223-73
GC18-52
S37-F067-81
F0224-81
F0225-84
S38-F067-74
S39-F067-74
S40-F067-78
S41-F067-76
GC19-53
F0226-70
F0227-78
S42-F067-68
S43-F067-80
S44-F067-69
F0228-86
S45-F067-57
GC20-59
S46-F067-66
GC21-64
S47-F067-64
S48-F067-61
S49-F067-60
GC22-53
GC23-61
GC24-52
S50-F067-55
GC25-61
S51-F067-73
S52-F067-78
S53-F067-54
S54-F067-68
S55-F067-64
GC26-59
F0229-71
F0230-67
S56-F067-73
S57-F067-55
GC27-55
GC28-59
F0231-71
F0232-81
S58-F067-65
S59-F067-84
S60-F067-72
S61-F067-75
F0233-85
GC29-65
F0234-87

In [8]:
print('Formato de tabla 1:')
cleaned_sheets['S1-F067-58']

Formato de tabla 1:

,0,1,2,3,4,5,6,7,8,9,10,11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alto: 14 a 19 puntos,NaN,Alto: 80 a 95 puntos
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Promedio: 7 a13 puntos,NaN,Promedio: 30 a 70 puntos
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alteración leve- moderado: 4 a 6 puntos,NaN,Bajo: 10 a 20 puntos
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alteración severa: 1 a 3 puntos,NaN,Déficit: <5 puntos
4,Dominio-Neuropsi Atención y Memoria- Test de B...,NaN,Puntuación obtenida,Puntuación normalizada,Interpretación,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Orientación,Tiempo,2/4 p,1,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Espacio,1/2 p,1,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Persona,1/1 p,11,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Atención y concentración,Dígitos en progresión,3/9 p,3,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Detección visual total *2 comisiones*,9,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Series sucesivas,2/3 p,10,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Memoria - Codificación,Curva de Memoria Volumen Promedio,5/12 p,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Memoria Verbal Espontánea total,4/12 p,9,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,Memoria Verbal Claves Total,2/12 p,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Memoria Verbal Reconocimiento *1 fr*,8/12 p,11,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,Memoria Lógica Promedio Historias,6/16 p,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Memoria Lógica Promedio Historias,5/16 p,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Memoria visual,Caras codificación,4/4 p,11,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,Reconocimiento Caras,2/2 p,11,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,Evocación figura semicompleja,15/36 p,10,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Gnosias,Figuras sobrepuestas (TB),20/20 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Lenguaje,Semejanzas (TB),8/12 p,60,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,Denominación (TB),14/14 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,Lectura de palabras (TB),6/6 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,Material verbal complejo (TB),9/9 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,Comprensión ejecución de ordenes (TB),13/16 p,5,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Praxias,Copia de figura compleja,32/36 p,12,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Gestos simbólicos (TB),10/10 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,Imitación de posturas (TB),8/8 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,"Funciones ejecutivas, conceptuales y motoras",Formación categorías,7/25 p,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,Fluidez verbal semántica,12,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,Fluidez verbal fonológica,6,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,Fluidez no verbal,5,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,Comprensión abstractacta-refranes (TB),10/10 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,Semejanzas (TB),8/12 p,60,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,Retención dígitos regresión,2/8 p,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,Cubos Regresión,2/9 p,5,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,[1]Perfil general de ejecución. Rango de edad:...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
print('Formato de tabla 0:')
cleaned_sheets['GC4-72']

Formato de tabla 0:

,0,1,2,3
0,FUNCIÓN EVALUADA (TEST EMPLEADO),P. Directa,Percentil o P. Directa,Clasificación
1,Orientación,NaN,NaN,NaN
2,Orientación en persona (TB),7 de 7,95,Alto
3,Orientación en espacio (TB),5 de 5,95,Alto
4,Orientación en tiempo (TB),20 de 23,5,Bajo
5,Capacidad atencional y velocidad de procesamiento,NaN,NaN,NaN
6,Atención sostenida auditiva (Dígitos directos ...,6/16 p,8,Promedio
7,Atención sostenida visual (TMT-A),32 sg,95,Alto
8,Atención selectiva visual (Búsqueda de símbolos),29,13,Promedio
9,Atención dividida visual (Clave de números-WAIS),42,11,Promedio
10,Lenguaje,NaN,NaN,NaN
11,Denominación de imágenes (TB),14/14 p,95,Alto
12,Comprensión de órdenes (TB),16/16 p,95,Alto
13,Material Verbal Complejo (TB),9 de 9,95,Alto
14,Memoria Verbal Test de Aprendizaje de Rey,NaN,NaN,NaN
15,Evocación inmediata Lista A ensayo 1,3/16 p,3/16 p,Promedio
16,Recuerdo inmediato Lista A ensayo 5,7/16 p,7/16 p,Bajo
17,Recuerdo inmediato Lista B,2/16 p,2/16 p,Bajo
18,Recuerdo libre a corto plazo,6/16 p,6/16 p,Bajo
19,Recuerdo libre a largo plazo,6/16 p,6/16 p,Bajo
20,Reconocimiento,12/16 p,12/16 p,Promedio
21,Memoria visual,NaN,NaN,NaN
22,Evocación diferida (Figura compleja de Rey),30/36 p,95,Alto
23,Capacidad Visuoperceptiva,NaN,NaN,NaN
24,Matrices (WAIS-IV),12/26 p,11,Promedio
25,Imágenes superpuestas (TB),20/20,95,Alto
26,Praxis,NaN,NaN,NaN
27,Constructiva (Figura compleja de Rey),36/36 p,85,Alto
28,Ideomotora Gestos simbólicos a la imitación -d...,10 de 10,95,Alto
29,Ideomotora Gestos simbólicos a la imitación -i...,10 de 10,95,Alto
30,Funciones ejecutivas,NaN,NaN,NaN
31,Memoria de Trabajo (Dígitos inversos WAIS-IV),6/16 p,10,Promedio
32,Memoria de Trabajo (Dígitos secuenciales WAIS-IV),7/16 p,10,Promedio
33,Test de fluidez fonológica FAS F,7,25,Promedio
34,Test de fluidez fonológica FAS A,11,55,Promedio
35,Test de fluidez fonológica FAS S,7,25,Promedio
36,Stroop Palabra,73,30,Promedio
37,Stroop Color,55,45,Promedio
38,Stroop Interferencia,25,30,Promedio
39,Semejanzas (TB),7/10 p,60,Promedio
40,Comprensión -abstracción (TB),12/12 p,95,Alto
41,Matrices (WAIS-IV),12/26 p,11,Promedio
42,Atención alternante (TMT B),120 sg.,65,Promedio

In [10]:
#Funcion para limpiar los nombres de las columnas y dejarlas mas estandarizadas
def clean_value(cadena):
  #Se eliminan espacios, se pasan a minusculas, se reemplazan espacios por guiones bajos, se eliminan acentos y caracteres especiales
  cadena = str(cadena).strip().lower().replace(' ', '_').replace('-','').replace("á", "a").replace("é", "e").replace("í", "i").replace("ó", "o").replace("ú", "u").replace(".","").replace("(","").replace(")","")
  return cadena

In [11]:
def detect_table_format(sheet, keywords=['espacio'], check_columns=[0, 1]):
    """
    Detecta el formato de la tabla basándose en palabras clave en columnas específicas.
    
    Parámetros:
    - sheet: DataFrame a analizar
    - keywords: lista de palabras clave a buscar
    - check_columns: índices de columnas a verificar (0=primera columna, 1=segunda columna)
    
    Retorna:
    - 0 si la palabra clave se encuentra en la primera columna
    - 1 si la palabra clave se encuentra en la segunda columna
    - 'no determinada' si no se encuentra en ninguna
    """
    
    for col_idx in check_columns:
        if col_idx < len(sheet.columns):
            # Vectorizar la búsqueda: convierte a string y aplica clean_value vectorizado
            col_data = sheet.iloc[:, col_idx].astype(str).str.lower().str.strip()
            
            # Aplicar transformaciones necesarias vectorizadas
            col_data_clean = col_data.str.replace(' ', '_', regex=False)
            col_data_clean = col_data_clean.str.replace('[áéíóú]', 
                lambda m: {'á':'a', 'é':'e', 'í':'i', 'ó':'o', 'ú':'u'}.get(m.group(0), m.group(0)), 
                regex=True)
            col_data_clean = col_data_clean.str.replace(r'[\-\.\(\)]', '', regex=True)
            
            # Verificar si alguna palabra clave existe en la columna
            pattern = '|'.join(keywords)
            if col_data_clean.str.contains(pattern, na=False, case=False).any():
                return col_idx
    
    return 'no determinada'

# Aplicar la detección a todas las hojas de manera vectorizada
type_of_table = {name: detect_table_format(sheet) for name, sheet in cleaned_sheets.items()}

In [25]:
print(f'Cantidad de datos tipo tabla 0: {list(type_of_table.values()).count(0)}')
print(f'Cantidad de datos tipo tabla 1: {list(type_of_table.values()).count(1)}')
# print(f'Cantidad de datos con formato no determinado: {list(type_of_table.values()).count("no determinada")}')
print(f'Cantidad total de datos procesados: {len(type_of_table)}')

Cantidad de datos tipo tabla 0: 36
Cantidad de datos tipo tabla 1: 81
Cantidad total de datos procesados: 125

In [13]:
def extract_patient_info(sheet_name):
    """Extrae la clasificación DC y edad del nombre de la hoja"""
    if 'F06' in str(sheet_name).upper():
        #Deterioro cognitivo leve
        dc = 1
    elif 'F02' in str(sheet_name).upper():
        #Demencia
        dc = 2
    elif 'GC' in str(sheet_name).upper():
        #Grupo de control
        dc = 0
    else: 
        dc = 'No determinada'
    
    age = str(sheet_name).split('-')[-1].strip()
    return dc, age

def extract_features_from_table(sheet, headers_col, value_col, features, headers_clean=None):
    """
    Extrae los valores de features de una tabla.
    
    Parámetros:
    - sheet: DataFrame de la tabla
    - headers_col: índice de la columna con headers
    - value_col: índice de la columna con valores
    - features: lista de features a buscar
    - headers_clean: diccionario precominado de headers limpios
    
    Retorna: diccionario con los valores encontrados
    """
    # Pre-procesar headers para limpiarlos
    if headers_clean is None:
        headers = sheet.iloc[:, headers_col].astype(str)
        headers_clean = headers.apply(clean_value)
    else:
        headers_clean = headers_clean
    
    result = {}
    
    # Crear un diccionario para búsqueda rápida: feature_clean -> índice de fila
    feature_to_idx = {}
    for feature in features:
        mask = headers_clean.str.contains(feature, case=False, na=False)
        if mask.any():
            feature_to_idx[feature] = headers_clean[mask].index[0]
    
    # Extraer los valores para cada feature
    for feature in features:
        if feature in feature_to_idx:
            idx = feature_to_idx[feature]
            result[feature] = sheet.iloc[idx, value_col]
        else:
            result[feature] = None
    
    return result

def search_values(data, features):
    """
    Busca y extrae los valores de features de todas las tablas,
    diferenciando entre tabla formato 0 y formato 1.
    """
    # Configuración de parámetros para cada formato de tabla
    table_configs = {
        0: {'headers_col': 0, 'value_col': 2, 'nivel_estudio': 0},
        1: {'headers_col': 1, 'value_col': 3, 'nivel_estudio': 1}
    }
    
    results = []
    
    # Procesar todas las hojas
    for sheet_name, sheet in data.items():
        table_format = type_of_table[sheet_name]
        
        # Ignorar si el formato no se pudo determinar
        if table_format == 'no determinada':
            continue
        
        config = table_configs[table_format]
        
        # Extraer información del paciente
        dc, age = extract_patient_info(sheet_name)
        
        # Pre-procesar headers una sola vez para esta tabla
        headers = sheet.iloc[:, config['headers_col']].astype(str)
        headers_clean = headers.apply(clean_value)
        
        # Extraer features
        features_dict = extract_features_from_table(
            sheet, 
            config['headers_col'], 
            config['value_col'], 
            features,
            headers_clean
        )
        
        # Construir registro del paciente
        patient_data = {
            'sheet_name': sheet_name,
            'nivel_estudio': config['nivel_estudio'],
            'dc': dc,
            'age': age,
            **features_dict
        }
        
        results.append(patient_data)
    
    # Convertir a DataFrame
    dataset_final = pd.DataFrame(results)
    return dataset_final

In [14]:
df = search_values(cleaned_sheets, features)

In [15]:
df.shape

(117, 67)

In [23]:
print(f'Grupo de control: {len(df[df["dc"] == 0])} personas')
print(f'Grupo de deterioro cognitivo: {len(df[df["dc"] == 1])} personas')
print(f'Grupo con demencia: {len(df[df["dc"] == 2])} personas')
# print(f'Cantidad total de personas con deterioro no determinada: {len(df[df["dc"] == "No determinada"])} personas, nombre de las hojas: {df[df["dc"] == "No determinada"]["sheet_name"].tolist()}')

Grupo de control: 27 personas
Grupo de deterioro cognitivo: 58 personas
Grupo con demencia: 32 personas

In [17]:
df[df['nivel_estudio'] == 1].head()

,sheet_name,nivel_estudio,dc,age,tiempo,persona,espacio,atencion_sostenida_auditiva,atencion_sostenida_visual,atencion_selectiva_visual,atencion_dividida_visual,digitos_en_progresion,cubos_progresion,deteccion_visual,deteccion_digitos_total,series_sucesivasdenominacion,comprension_de_ordenes,material_verbal_complejo,semejanzas,lectura_de_palabras,comprension_ejecicion_de_ordenes,evocacion_inmediata_lista_a,recuerdo_inmediato_lista_a,recuerdo_inmediato_lista_b,recuerdo_libre_a_corto_plazo,recuerdo_libre_a_largo_plazo,recuerdo_libre_a_largo_plazo_clave,reconocimiento,curva_de_memoria_volumen_promedio,memoria_verbal_espontanea_total,memoria_verbal_claves_total,memoria_verbal_reconocimiento_total,memoria_lógica_promedio_historias,evocacion_diferida,reconocimiento_inmediato_ensayo_2,reconocimiento_diferido_ensayo_3,caras_codificación,reconocimiento_caras,evocacion_figura_semicompleja,imagenes_superpuesta,constructiva,ideomotora_gestos_simbolicos_a_la_orden_derecha,ideomotora_gestos_simbolicos_a_la_orden_izquierda,ideomotora_gestos_simbolicos_a_la_imitacion_derecha,ideomotora_gestos_simbolicos_a_la_imitacion_izquierda,copia_de_figura_compleja,gestos_simbolicos,imitacion_de_posturas,memoria_de_trabajo_digitos_inversos,memoria_de_trabajo_digitos_secuenciales,test_de_fluidez_fonologica_fas_f,test_de_fluidez_fonologica_fas_a,test_de_fluidez_fonologica_fas_s,evocacion_categorial_semantica,matrices,comprension_abstraccion,atencion_alternante,stroop_a,stroop_b,stroop_c,stroop_palabra,stroop_colores,stroop_interferencia,fluidez_verbal_semantica,fluidez_verbal_fonologica,fluidez_no_verbal,retencion_digitos_regresion
0,S1-F067-58,1,1,58,1,11.0,1.0,NaN,None,NaN,NaN,3.0,NaN,6.0,NaN,None,None,95,60,95,None,None,None,None,None,None,None,11,7.0,9.0,6.0,NaN,None,None,None,None,None,11.0,10.0,None,None,None,None,None,None,12.0,95,95,NaN,NaN,None,None,None,None,NaN,None,None,NaN,NaN,None,None,None,None,6.0,6.0,7.0,6.0
13,GC8-79,1,0,79,10,10.0,10.0,NaN,None,NaN,NaN,13.0,12.0,9.0,NaN,None,None,95,95,95,None,None,None,None,None,None,None,14,11.0,7.0,5.0,14.0,None,None,None,None,None,11.0,13.0,95,None,95,95,None,None,NaN,95,None,NaN,NaN,None,None,None,None,NaN,None,None,NaN,NaN,None,None,None,None,16.0,14.0,8.0,14.0
14,S5-F067-73,1,1,73,11,11.0,11.0,NaN,None,NaN,NaN,10.0,5.0,5.0,NaN,None,None,95,80,95,None,None,None,None,None,None,None,12,7.0,9.0,12.0,12.0,None,None,None,None,None,13.0,4.0,95,None,95,95,None,None,NaN,95,None,NaN,NaN,None,None,None,None,NaN,None,None,NaN,NaN,None,None,None,None,9.0,7.0,8.0,9.0
15,F023-87,1,2,87,1,1.0,1.0,NaN,None,NaN,NaN,9.0,2.0,2.0,NaN,None,None,<5,<5,<5,None,None,None,None,None,None,None,6,8.0,6.0,5.0,6.0,None,None,None,None,None,8.0,5.0,<5,None,95,95,None,None,NaN,95,None,NaN,NaN,None,None,None,None,NaN,None,None,NaN,NaN,None,None,None,None,6.0,3.0,5.0,1.0
16,F024-72,1,2,72,1,1.0,1.0,NaN,None,NaN,NaN,9.0,6.0,5.0,NaN,None,None,5,80,None,None,None,None,None,None,None,None,12,10.0,7.0,5.0,NaN,None,None,None,None,None,5.0,6.0,20,None,95,95,None,None,NaN,95,None,NaN,NaN,None,None,None,None,NaN,None,None,NaN,NaN,None,None,None,None,6.0,7.0,1.0,8.0

In [18]:
df[df['nivel_estudio'] == 0].head()

,sheet_name,nivel_estudio,dc,age,tiempo,persona,espacio,atencion_sostenida_auditiva,atencion_sostenida_visual,atencion_selectiva_visual,atencion_dividida_visual,digitos_en_progresion,cubos_progresion,deteccion_visual,deteccion_digitos_total,series_sucesivasdenominacion,comprension_de_ordenes,material_verbal_complejo,semejanzas,lectura_de_palabras,comprension_ejecicion_de_ordenes,evocacion_inmediata_lista_a,recuerdo_inmediato_lista_a,recuerdo_inmediato_lista_b,recuerdo_libre_a_corto_plazo,recuerdo_libre_a_largo_plazo,recuerdo_libre_a_largo_plazo_clave,reconocimiento,curva_de_memoria_volumen_promedio,memoria_verbal_espontanea_total,memoria_verbal_claves_total,memoria_verbal_reconocimiento_total,memoria_lógica_promedio_historias,evocacion_diferida,reconocimiento_inmediato_ensayo_2,reconocimiento_diferido_ensayo_3,caras_codificación,reconocimiento_caras,evocacion_figura_semicompleja,imagenes_superpuesta,constructiva,ideomotora_gestos_simbolicos_a_la_orden_derecha,ideomotora_gestos_simbolicos_a_la_orden_izquierda,ideomotora_gestos_simbolicos_a_la_imitacion_derecha,ideomotora_gestos_simbolicos_a_la_imitacion_izquierda,copia_de_figura_compleja,gestos_simbolicos,imitacion_de_posturas,memoria_de_trabajo_digitos_inversos,memoria_de_trabajo_digitos_secuenciales,test_de_fluidez_fonologica_fas_f,test_de_fluidez_fonologica_fas_a,test_de_fluidez_fonologica_fas_s,evocacion_categorial_semantica,matrices,comprension_abstraccion,atencion_alternante,stroop_a,stroop_b,stroop_c,stroop_palabra,stroop_colores,stroop_interferencia,fluidez_verbal_semantica,fluidez_verbal_fonologica,fluidez_no_verbal,retencion_digitos_regresion
1,GC1-60,0,0,60,NaN,NaN,NaN,6.0,NaN,9.0,8.0,NaN,NaN,NaN,NaN,None,95,30,10,None,None,3/16 p,7/16 p,6/16 p,7/16 p,6/16 p,None,12/16 p,NaN,NaN,NaN,NaN,None,NaN,None,None,None,NaN,NaN,95,NaN,95,None,None,None,NaN,95,None,7.0,6.0,None,None,None,NaN,8.0,95,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN
2,GC2-62,0,0,62,95,95.0,95.0,14.0,60,9.0,11.0,NaN,NaN,NaN,NaN,None,95,95,70,None,None,6/16 p,9/16 p,4/16 p,5/16 p,8/16 p,None,15/16 p,NaN,NaN,NaN,NaN,None,75,None,None,None,NaN,NaN,95,85,95,95,None,None,NaN,95,None,12.0,11.0,None,None,None,None,13.0,70,85,NaN,NaN,25,45,None,35,NaN,NaN,NaN,NaN
3,F021-72,0,2,72,95,95.0,95.0,6.0,<5,7.0,6.0,NaN,NaN,NaN,NaN,None,95,95,95,95,None,2/16 p,5/16 p,2/16 p,2/16 p,3/16 p,None,15/16 p,NaN,NaN,NaN,NaN,None,5,None,None,None,NaN,NaN,95,<5,95,95,95,95,NaN,95,None,4.0,6.0,None,None,None,<5,NaN,<5,<5,NaN,NaN,<5,<5,None,<5,NaN,NaN,NaN,NaN
4,S2-F067-53,0,1,53,95,95.0,95.0,8.0,<5,5.0,4.0,NaN,NaN,NaN,NaN,None,5,95,5,None,None,2/16 p,9/16 p,4/16 p,7/16 p,6/16 p,None,8/16 p,NaN,NaN,NaN,NaN,None,40,None,None,None,NaN,NaN,95,15,95,95,95,95,NaN,95,None,7.0,5.0,None,None,None,10,NaN,20,<5,NaN,NaN,5,<5,None,<5,NaN,NaN,NaN,NaN
5,GC3-60,0,0,60,95,95.0,95.0,10.0,50,9.0,9.0,NaN,NaN,NaN,NaN,None,95,20,40,None,None,6/16 p,13/16 p,6/16 p,10/16 p,8/16 p,None,14/16 p,NaN,NaN,NaN,NaN,None,75,None,None,None,NaN,NaN,95,85,95,95,95,95,NaN,95,None,12.0,NaN,>95,75,80,>95,11.0,90,85,90.0,85.0,55,None,None,None,NaN,NaN,NaN,NaN

In [24]:
df.sample(20)

,sheet_name,nivel_estudio,dc,age,tiempo,persona,espacio,atencion_sostenida_auditiva,atencion_sostenida_visual,atencion_selectiva_visual,atencion_dividida_visual,digitos_en_progresion,cubos_progresion,deteccion_visual,deteccion_digitos_total,series_sucesivasdenominacion,comprension_de_ordenes,material_verbal_complejo,semejanzas,lectura_de_palabras,comprension_ejecicion_de_ordenes,evocacion_inmediata_lista_a,recuerdo_inmediato_lista_a,recuerdo_inmediato_lista_b,recuerdo_libre_a_corto_plazo,recuerdo_libre_a_largo_plazo,recuerdo_libre_a_largo_plazo_clave,reconocimiento,curva_de_memoria_volumen_promedio,memoria_verbal_espontanea_total,memoria_verbal_claves_total,memoria_verbal_reconocimiento_total,memoria_lógica_promedio_historias,evocacion_diferida,reconocimiento_inmediato_ensayo_2,reconocimiento_diferido_ensayo_3,caras_codificación,reconocimiento_caras,evocacion_figura_semicompleja,imagenes_superpuesta,constructiva,ideomotora_gestos_simbolicos_a_la_orden_derecha,ideomotora_gestos_simbolicos_a_la_orden_izquierda,ideomotora_gestos_simbolicos_a_la_imitacion_derecha,ideomotora_gestos_simbolicos_a_la_imitacion_izquierda,copia_de_figura_compleja,gestos_simbolicos,imitacion_de_posturas,memoria_de_trabajo_digitos_inversos,memoria_de_trabajo_digitos_secuenciales,test_de_fluidez_fonologica_fas_f,test_de_fluidez_fonologica_fas_a,test_de_fluidez_fonologica_fas_s,evocacion_categorial_semantica,matrices,comprension_abstraccion,atencion_alternante,stroop_a,stroop_b,stroop_c,stroop_palabra,stroop_colores,stroop_interferencia,fluidez_verbal_semantica,fluidez_verbal_fonologica,fluidez_no_verbal,retencion_digitos_regresion
18,F025-82,1,2,82,1,11.0,11.0,NaN,None,NaN,NaN,10.0,7.0,6.0,3.0,None,None,40,95,None,None,None,None,None,None,None,None,6,5.0,5.0,5.0,6.0,None,None,None,None,None,7.0,3.0,95,None,95,95,95,95,NaN,95,None,NaN,NaN,None,None,None,None,NaN,None,None,NaN,NaN,None,None,None,None,8.0,11.0,4.0,9.0
21,GC10-65,1,0,65,10,10.0,10.0,NaN,None,NaN,NaN,9.0,9.0,15.0,NaN,None,None,95,95,None,None,None,None,None,None,None,None,14,14.0,16.0,14.0,14.0,None,None,None,None,None,11.0,9.0,95,None,None,None,None,None,NaN,None,None,NaN,NaN,None,None,None,None,NaN,None,None,NaN,NaN,None,None,None,None,16.0,19.0,1.0,11.0
81,S40-F067-78,1,1,78,11,11.0,11.0,NaN,None,NaN,NaN,10.0,NaN,12.0,NaN,None,95,95,30,None,None,None,None,None,None,None,None,9,7.0,5.0,8.0,NaN,None,None,None,None,None,13.0,10.0,None,None,None,None,None,None,9.0,95,95,NaN,NaN,None,None,None,None,NaN,None,None,10.0,NaN,None,None,None,None,7.0,7.0,8.0,6.0
60,S26-F067-81,1,1,81,1,11.0,1.0,NaN,None,NaN,NaN,15.0,NaN,9.0,NaN,None,95,95,<5,None,None,None,None,None,None,None,None,17,10.0,13.0,6.0,NaN,None,None,None,None,None,NaN,10.0,None,None,None,None,None,None,9.0,None,None,NaN,NaN,None,None,None,None,NaN,None,None,NaN,NaN,None,None,None,None,10.0,6.0,8.0,7.0
108,S57-F067-55,0,1,55,95,95.0,95.0,8.0,45,6.0,6.0,NaN,NaN,NaN,NaN,None,95,95,<5,None,None,2/15 p,7/15 p,2/15 p,5/15 p,5/15 p,None,12/15 p,NaN,NaN,NaN,NaN,None,25,None,None,None,NaN,NaN,None,75,None,None,None,None,NaN,None,None,6.0,6.0,None,None,None,None,NaN,<5,<15,NaN,NaN,10,10,None,15,NaN,NaN,NaN,NaN
4,S2-F067-53,0,1,53,95,95.0,95.0,8.0,<5,5.0,4.0,NaN,NaN,NaN,NaN,None,5,95,5,None,None,2/16 p,9/16 p,4/16 p,7/16 p,6/16 p,None,8/16 p,NaN,NaN,NaN,NaN,None,40,None,None,None,NaN,NaN,95,15,95,95,95,95,NaN,95,None,7.0,5.0,None,None,None,10,NaN,20,<5,NaN,NaN,5,<5,None,<5,NaN,NaN,NaN,NaN
93,S47-F067-64,1,1,64,11,11.0,11.0,NaN,None,NaN,NaN,10.0,NaN,9.0,NaN,None,None,95,<5,None,None,None,None,None,None,None,None,14,9.0,5.0,8.0,NaN,None,None,None,None,None,7.0,6.0,None,None,None,None,None,None,8.0,None,95,NaN,NaN,None,None,None,None,NaN,None,None,8.0,NaN,None,None,None,None,7.0,9.0,5.0,9.0
40,GC13-74,0,0,74,95,95.0,95.0,11.0,None,12.0,11.0,NaN,NaN,NaN,NaN,None,None,None,95,None,None,5/15 p,11/15 p,5/15 p,5/15 p,4/15 p,None,14/15 p,NaN,NaN,NaN,NaN,None,50,None,None,None,NaN,NaN,None,None,None,None,None,None,NaN,95,95,10.0,9.0,None,None,None,None,14.0,None,None,65.0,50.0,None,None,None,40,NaN,NaN,NaN,NaN
114,F0233-85,1,2,85,1,1.0,1.0,NaN,None,NaN,NaN,4.0,NaN,2.0,NaN,None,None,95,None,None,None,None,None,None,None,None,None,12,5.0,7.0,7.0,12.0,None,None,None,None,None,11.0,4.0,95,None,None,None,None,None,NaN,95,95,NaN,NaN,None,None,None,None,NaN,None,None,1.0,NaN,None,None,None,None,3.0,1.0,1.0,11.0
71,F0222-64,0,2,64,5,95.0,5.0,4.0,<15,3.0,3.0,NaN,NaN,NaN,NaN,None,95,95,10,None,None,2/16 p,2/16 p,1/16 p,0/16 p,0/16 p,None,15/16 p,NaN,NaN,NaN,NaN,None,<5,None,None,None,NaN,NaN,None,5,95,95,95,None,NaN,95,None,7.0,5.0,<5,<5,10,None,NaN,10,<15,NaN,NaN,10,5,None,<5,NaN,NaN,NaN,NaN
73,GC17-60,0,0,60,95,95.0,95.0,8.0,85,10.0,10.0,NaN,NaN,NaN,NaN,None,95,5,40,None,None,5/16 p,10/16 p,5/16 p,7/16 p,7/16 p,None,16/16 p,NaN,NaN,NaN,NaN,None,40,None,None,None,NaN,NaN,None,85,None,None,None,None,NaN,None,None,4.0,8.0,None,None,None,None,7.0,<5,75,NaN,NaN,55,45,None,55,NaN,NaN,NaN,NaN
39,F0212-65,1,2,65,1,1.0,1.0,NaN,None,NaN,NaN,9.0,2.0,2.0,NaN,None,None,<5,<5,95,None,None,None,None,None,None,None,6,6.0,6.0,6.0,6.0,None,None,None,None,None,8.0,NaN,<5,None,None,None,None,None,NaN,None,None,NaN,NaN,None,None,None,None,NaN,None,None,NaN,NaN,None,None,None,None,6.0,3.0,9.0,7.0
101,S53-F067-54,0,1,54,95,95.0,95.0,3.0,45,5.0,5.0,NaN,NaN,NaN,NaN,None,95,95,4,None,None,1/15 p,6/15 p,3/15 p,2/15 p,3/15 p,None,10/15 p,NaN,NaN,NaN,NaN,None,45,None,None,None,NaN,NaN,None,70,None,None,None,None,NaN,None,None,5.0,5.0,None,None,None,5,5.0,<5,<5,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN
53,S24-F067-96,1,1,96,1,11.0,11.0,NaN,None,NaN,NaN,5.0,NaN,4.0,9.0,None,None,95,<5,None,None,None,None,None,None,None,None,6,4.0,6.0,6.0,NaN,None,None,None,None,None,11.0,6.0,None,95,None,None,None,None,9.0,95,None,NaN,NaN,None,None,None,None,NaN,None,None,NaN,NaN,None,None,None,None,7.0,6.0,8.0,7.0
87,S43-F067-80,1,1,80,3,11.0,11.0,NaN,None,NaN,NaN,13.0,NaN,11.0,NaN,None,None,95,80,None,None,None,None,None,None,None,None,10,12.0,6.0,6.0,NaN,None,None,None,None,None,8.0,8.0,None,None,None,None,None,None,6.0,95,95,NaN,NaN,None,None,None,None,NaN,None,None,NaN,NaN,None,None,None,None,9.0,12.0,5.0,7.0
91,S46-F067-66,0,1,66,95,95.0,95.0,8.0,55,9.0,10.0,NaN,NaN,NaN,NaN,None,95,None,None,None,None,4/15 p,8/15 p,4/15 p,5/15 p,5/15 p,None,13/15 p,NaN,NaN,NaN,NaN,None,55,None,None,None,NaN,NaN,None,55,None,None,None,None,NaN,None,None,7.0,9.0,75,65,70,None,NaN,<5,30,NaN,NaN,45,45,None,15,NaN,NaN,NaN,NaN
5,GC3-60,0,0,60,95,95.0,95.0,10.0,50,9.0,9.0,NaN,NaN,NaN,NaN,None,95,20,40,None,None,6/16 p,13/16 p,6/16 p,10/16 p,8/16 p,None,14/16 p,NaN,NaN,NaN,NaN,None,75,None,None,None,NaN,NaN,95,85,95,95,95,95,NaN,95,None,12.0,NaN,>95,75,80,>95,11.0,90,85,90.0,85.0,55,None,None,None,NaN,NaN,NaN,NaN
100,S52-F067-78,0,1,78,95,95.0,95.0,9.0,<20,5.0,4.0,NaN,NaN,NaN,NaN,None,<5,95,80,95,None,4/16 p,7/16 p,3/16 p,0/16 p,3/16 p,None,11/16 p,NaN,NaN,NaN,NaN,None,20,None,None,None,NaN,NaN,10,5,<5,<5,<5,<5,NaN,<5,None,9.0,9.0,<5,<5,15,55,8.0,70,No logrado,NaN,NaN,None,None,None,None,NaN,NaN,NaN,NaN
31,F028-70,1,2,70,1,1.0,10.0,NaN,None,NaN,NaN,9.0,1.0,8.0,1.0,None,None,<5,<5,None,None,None,None,None,None,None,None,14,5.0,7.0,4.0,14.0,None,None,None,None,None,5.0,4.0,5,None,95,None,None,None,NaN,95,None,NaN,NaN,None,None,None,None,NaN,None,None,NaN,NaN,None,None,None,None,1.0,1.0,1.0,5.0
11,GC7-70,0,0,70,95,95.0,95.0,10.0,95,9.0,12.0,NaN,NaN,NaN,NaN,None,95,95,70,95,None,7/16 p,14/16 p,7/16 p,13/16 p,15/16 p,None,16/16 p,NaN,NaN,NaN,NaN,None,>95,None,None,None,NaN,NaN,95,85,None,None,None,None,NaN,95,None,10.0,14.0,20,65,<5,25,11.0,95,90,NaN,NaN,75,60,None,75,NaN,NaN,NaN,NaN

In [ ]:
# menor a 5 alteracion Alteración Severa
# 5 a 24 bajo   
# 25 a 85 promedio
# 85 a 100 Alto



#Alteracion severa - 1,2,3
#bajo - 4,5,6
#promedio - 7-13
#Alto - 14-18