In [419]:
import pandas as pd
from dotenv import dotenv_values
import requests
from io import BytesIO

In [420]:
#Mostrar todas la columnas de los DataFrame
pd.set_option("display.max_columns", None)  # mostrar todas las columnas

In [421]:
config = dotenv_values(dotenv_path=".env")

In [422]:
url = "https://raw.githubusercontent.com/Nicolasg2c/dc_model_ts/main/common/data/datos_deterioro_cognitivo.xlsx"

headers = {"Authorization": f"Bearer {config['GITHUB_TOKEN']}"}
r = requests.get(url, headers=headers, timeout=30)
r.raise_for_status()  # Check if the request was successful

xlsx_data = pd.read_excel(BytesIO(r.content), header=None, sheet_name=None, engine="openpyxl")

In [423]:
##Mapeo de las columnas a buscar en cada hoja
features = [
    
   #Tabla 0 nivel de estudio: Escolaridad baja
   #Tabla 1 nivel de estudio: Escolaridad alta
    
  #####Orientación
  
  #tabla 0 y tabla 1 con estos nombre ambos quedan en la misma columna
  'tiempo',
  'persona',
  'espacio', 
  
  #####Capacidad atencional

  #tabla 0
  'atencion_sostenida_auditiva', #'digitos_en_progresion',
  'atencion_sostenida_visual', #no tiene equivalencia
  'atencion_selectiva_visual', #no tiene equivalencia
  'atencion_dividida_visual', #Deteccion visual
  #tabla 1
  'digitos_en_progresion',
  'cubos_progresion',
  'deteccion_visual',
  'deteccion_digitos_total',
  'series_sucesivas',

  #####Lenguaje
  
  #tabla 0
  'denominacion',
  'comprension_de_ordenes', #Es posible que no sea crucial
  'material_verbal_complejo', #Es posible que no sea crucial
  # #tabla 1
  # 'denominacion'
  #Semenjanzas puede estar en funciones ejecutivas o lenguaje
  'semejanzas',
  'lectura_de_palabras', # es posible que aparezca igual en ambas tablas
  # 'material_verbal_complejo',
  'comprension_ejecucion_de_ordenes',

  #####California verbal learning test | aprendizaje verbal del rey | memoria verbal
  
  #verbal del rey 
  
  #Tabla 0 - california verbal learning test
  'evocacion_inmediata_lista_a',
  'recuerdo_inmediato_lista_a',
  'recuerdo_inmediato_lista_b',
  'recuerdo_libre_a_corto_plazo',
  'recuerdo_libre_a_largo_plazo',
  'recuerdo_libre_a_largo_plazo',
  'reconocimiento',
  #tabla 0 - aprendizaje verbal del rey
  'evocacion_inmediata_lista_a',
  'recuerdo_inmediato_lista_b',
  'recuerdo_libre_a_corto_plazo',
  'recuerdo_libre_a_largo_plazo',
  'reconocimiento',
  #Tabla 1 #No tiene equivalencia con los otros test de la tabla 0
  'curva_de_memoria_volumen_promedio', 
  'memoria_verbal_espontanea_total',
  'memoria_verbal_claves_total',
  'memoria_verbal_reconocimiento',
  'memoria_lógica_promedio_historias',
  'memoria_lógica_promedio_historias',

  #####Memoria visual
  
  #Tabla 0
  'evocacion_diferida',#evocacion_figura_semicompleja
  #Tabla 1
  'caras_codificación',
  'reconocimiento_caras',
  'evocacion_figura_semicompleja',

  #####Genosias | capacidad visuoperceptiva
  
  #tabla 0 y tabla 1
  'imagenes_superpuesta',

  #####Praxis | praxias
  
  #Tabla 0
  'constructiva', #copia_de_figura_compleja
  'ideomotora_gestos_simbolicos_a_la_orden_derecha',
  'ideomotora_gestos_simbolicos_a_la_orden_izquierda',
  'ideomotora_gestos_simbolicos_a_la_imitacion_derecha',
  'ideomotora_gestos_simbolicos_a_la_imitacion_izquierda',
  #Tabla 1
  'copia_de_figura_compleja',
  'gestos_simbolicos',
  'imitacion_de_posturas',

  #####Funciones ejecutivas
  
  #Tabla 0
  'memoria_de_trabajo_digitos_inversos', #retencion_digitos_regresion
  'memoria_de_trabajo_digitos_secuenciales', #no tiene equivalencia
  'test_de_fluidez_fonologica_fas_f',
  'test_de_fluidez_fonologica_fas_a',
  'test_de_fluidez_fonologica_fas_s',
  'evocacion_categorial_semantica',
  'semejanzas',
  'matrices',
  'comprension_abstraccion', #comprension_abstraccion
  'atencion_alternante',
  'stroop_a',
  'stroop_b',
  'stroop_c',
  'stroop_palabra',
  'stroop_colores',
  'stroop_interferencia', #stroop_interferencia
  #tabla 1
  'semejanzas', # se puede presentar aqui o en lenguaje
  'fluidez_verbal_semantica',
  'fluidez_verbal_fonologica',
  'fluidez_no_verbal',
  'retencion_digitos_regresion',
  'cubos_regresion',
  ]

In [424]:
##Mapeo de las columnas a buscar en cada hoja - Tabla 0 
features_tabla_0 = [
    
   #Tabla 0 nivel de estudio: Escolaridad baja
   #Tabla 1 nivel de estudio: Escolaridad alta
    
  #####Orientación
  
  #tabla 0 y tabla 1 con estos nombre ambos quedan en la misma columna
  'tiempo',
  'persona',
  'espacio', 
  
  #####Capacidad atencional

  #tabla 0
  'atencion_sostenida_auditiva', #'digitos_en_progresion',
  'atencion_sostenida_visual', #no tiene equivalencia
  'atencion_selectiva_visual', #no tiene equivalencia
  'atencion_dividida_visual', #Deteccion visual

  #####Lenguaje
  
  #tabla 0
  'denominacion',
  'comprension_de_ordenes', #Es posible que no sea crucial
  'material_verbal_complejo', #Es posible que no sea crucial

  #####California verbal learning test | aprendizaje verbal del rey | memoria verbal
  
  #verbal del rey 
  
  #Tabla 0 - california verbal learning test
  'evocacion_inmediata_lista_a',
  'recuerdo_inmediato_lista_a',
  'recuerdo_inmediato_lista_b',
  'recuerdo_libre_a_corto_plazo',
  'recuerdo_libre_a_largo_plazo',
  'recuerdo_libre_a_largo_plazo',
  'reconocimiento',
  #tabla 0 - aprendizaje verbal del rey
  'evocacion_inmediata_lista_a',
  'evocacion_inmediata_lista_b',
  'recuerdo_inmediato_lista_b',
  'recuerdo_libre_a_corto_plazo',
  'recuerdo_libre_a_largo_plazo',
  'reconocimiento',


  #####Memoria visual
  
  #Tabla 0
  'evocacion_diferida',#evocacion_figura_semicompleja

  #####Genosias | capacidad visuoperceptiva
  
  #tabla 0 y tabla 1
  'imagenes_superpuesta',

  #####Praxis | praxias
  
  #Tabla 0
  'constructiva', #copia_de_figura_compleja
  'ideomotora_gestos_simbolicos_a_la_orden_derecha',
  'ideomotora_gestos_simbolicos_a_la_orden_izquierda',
  'ideomotora_gestos_simbolicos_a_la_imitacion_derecha',
  'ideomotora_gestos_simbolicos_a_la_imitacion_izquierda',

  #####Funciones ejecutivas
  
  #Tabla 0
  'memoria_de_trabajo_digitos_inversos', #retencion_digitos_regresion
  'memoria_de_trabajo_digitos_secuenciales', #no tiene equivalencia
  'test_de_fluidez_fonologica_fas_f',
  'test_de_fluidez_fonologica_fas_a',
  'test_de_fluidez_fonologica_fas_s',
  'evocacion_categorial_semantica',
  'semejanzas',
  'matrices',
  'comprension_abstraccion', #comprension_abstraccion
  'atencion_alternante',
  'stroop_a',
  'stroop_b',
  'stroop_c',
  'stroop_palabra',
  'stroop_colores',
  'stroop_interferencia', #stroop_interferencia
  ]

In [425]:
##Mapeo de las columnas a buscar en cada hoja - Tabla 1
features_tabla_1 = [
    
   #Tabla 0 nivel de estudio: Escolaridad baja
   #Tabla 1 nivel de estudio: Escolaridad alta
    
  #####Orientación
  
  #tabla 0 y tabla 1 con estos nombre ambos quedan en la misma columna
  'tiempo',
  'persona',
  'espacio', 
  
  #####Capacidad atencional

  #tabla 1
  'digitos_en_progresion',
  'cubos_progresion',
  'deteccion_visual',
  'deteccion_digitos_total',
  'series_sucesivas',

  #####Lenguaje
  

  # #tabla 1
  'denominacion',
  'semejanzas',
  'lectura_de_palabras', # es posible que aparezca igual en ambas tablas
  'material_verbal_complejo',
  'comprension_ejecucion_de_ordenes',

  #####California verbal learning test | aprendizaje verbal del rey | memoria verbal
  
  #verbal del rey 
  
  #Tabla 1 #No tiene equivalencia con los otros test de la tabla 0
  'curva_de_memoria_volumen_promedio', 
  'memoria_verbal_espontanea_total',
  'memoria_verbal_claves_total',
  'memoria_verbal_reconocimiento',
  'memoria_logica_promedio_historias',

  #####Memoria visual
  
  #Tabla 1
  'caras_codificacion',
  'reconocimiento_caras',
  'evocacion_figura_semicompleja',

  #####Genosias | capacidad visuoperceptiva
  
  #tabla 0 y tabla 1
  'imagenes_superpuesta',

  #####Praxis | praxias
  
  #Tabla 1
  'copia_de_figura_compleja',
  'gestos_simbolicos',
  'imitacion_de_posturas',

  #####Funciones ejecutivas

  #tabla 1
  'semejanzas', # se puede presentar aqui o en lenguaje
  'fluidez_verbal_semantica',
  'fluidez_verbal_fonologica',
  'fluidez_no_verbal',
  'retencion_digitos_regresion',
  'cubos_regresion',
  ]

In [426]:
##Mapeo de las columnas a buscar en cada hoja - Tabla 1 y 2
features_tablas = [
    
   #Tabla 0 nivel de estudio: Escolaridad baja
   #Tabla 1 nivel de estudio: Escolaridad alta
    
  #####Orientación
  
  #tabla 0 y tabla 1 con estos nombre ambos quedan en la misma columna
  'tiempo',
  'persona',
  'espacio', 
  
  #####Capacidad atencional

  #tabla 0
  'atencion_sostenida_auditiva', #'digitos_en_progresion',
  'atencion_dividida_visual', #deteccion_visual
  #tabla 1
  'digitos_en_progresion',
  'deteccion_visual',

  #####Lenguaje
  
  #tabla 0
  'denominacion',
  # 'comprension_de_ordenes', #comprension_ejecucion_de_ordenes
  'material_verbal_complejo',
  #  'lectura_de_palabras',
  # #tabla 1
  'semejanzas',
#   'lectura_de_palabras', # es posible que aparezca igual en ambas tablas
  # 'comprension_ejecucion_de_ordenes',

  #####Memoria visual
  
  #Tabla 0
  'evocacion_diferida',#evocacion_figura_semicompleja
  #Tabla 1
  'evocacion_figura_semicompleja',

  #####Genosias | capacidad visuoperceptiva
  
  #tabla 0 y tabla 1
  # 'imagenes_superpuesta',

  #####Praxis | praxias
  
  #Tabla 0
  # 'constructiva', #copia_de_figura_compleja
  #Tabla 1
  # 'copia_de_figura_compleja',

  #####Funciones ejecutivas
  
  #Tabla 0
  'memoria_de_trabajo_digitos_inversos', #retencion_digitos_regresion
  # 'comprension_abstraccion', #comprension_abstraccion
  # 'stroop_interferencia', #stroop_interferencia
  #tabla 1
  'retencion_digitos_regresion',
  ]

In [427]:
cleaned_sheets = {}
for name, sheet in xlsx_data.items():
    sheet = sheet.dropna(how="all")       # eliminar filas vacías
    sheet = sheet.reset_index(drop=True)
    cleaned_sheets[name] = sheet

In [428]:
print(f'Cantidad de datos {len(cleaned_sheets)} \n')
print(f'Nombre de las hojas procesadas:\n ')
# for name, sheet in cleaned_sheets.items():
    # print(f'{name}')

Cantidad de datos 125

Nombre de las hojas procesadas:

In [429]:
print('Formato de tabla 1:')
cleaned_sheets['S1-F067-58']

Formato de tabla 1:

,0,1,2,3,4,5,6,7,8,9,10,11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alto: 14 a 19 puntos,NaN,Alto: 80 a 95 puntos
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Promedio: 7 a13 puntos,NaN,Promedio: 30 a 70 puntos
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alteración leve- moderado: 4 a 6 puntos,NaN,Bajo: 10 a 20 puntos
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alteración severa: 1 a 3 puntos,NaN,Déficit: <5 puntos
4,Dominio-Neuropsi Atención y Memoria- Test de B...,NaN,Puntuación obtenida,Puntuación normalizada,Interpretación,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Orientación,Tiempo,2/4 p,1,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Espacio,1/2 p,1,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Persona,1/1 p,11,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Atención y concentración,Dígitos en progresión,3/9 p,3,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Detección visual total *2 comisiones*,9,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Series sucesivas,2/3 p,10,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Memoria - Codificación,Curva de Memoria Volumen Promedio,5/12 p,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Memoria Verbal Espontánea total,4/12 p,9,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,Memoria Verbal Claves Total,2/12 p,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Memoria Verbal Reconocimiento *1 fr*,8/12 p,11,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,Memoria Lógica Promedio Historias,6/16 p,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Memoria Lógica Promedio Historias,5/16 p,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Memoria visual,Caras codificación,4/4 p,11,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,Reconocimiento Caras,2/2 p,11,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,Evocación figura semicompleja,15/36 p,10,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Gnosias,Figuras sobrepuestas (TB),20/20 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Lenguaje,Semejanzas (TB),8/12 p,60,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,Denominación (TB),14/14 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,Lectura de palabras (TB),6/6 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,Material verbal complejo (TB),9/9 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,Comprensión ejecución de ordenes (TB),13/16 p,5,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Praxias,Copia de figura compleja,32/36 p,12,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Gestos simbólicos (TB),10/10 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,Imitación de posturas (TB),8/8 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,"Funciones ejecutivas, conceptuales y motoras",Formación categorías,7/25 p,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,Fluidez verbal semántica,12,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,Fluidez verbal fonológica,6,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,Fluidez no verbal,5,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,Comprensión abstractacta-refranes (TB),10/10 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,Semejanzas (TB),8/12 p,60,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,Retención dígitos regresión,2/8 p,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,Cubos Regresión,2/9 p,5,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,[1]Perfil general de ejecución. Rango de edad:...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [430]:
print('Formato de tabla 0:')
cleaned_sheets['GC4-72']

Formato de tabla 0:

,0,1,2,3
0,FUNCIÓN EVALUADA (TEST EMPLEADO),P. Directa,Percentil o P. Directa,Clasificación
1,Orientación,NaN,NaN,NaN
2,Orientación en persona (TB),7 de 7,95,Alto
3,Orientación en espacio (TB),5 de 5,95,Alto
4,Orientación en tiempo (TB),20 de 23,5,Bajo
5,Capacidad atencional y velocidad de procesamiento,NaN,NaN,NaN
6,Atención sostenida auditiva (Dígitos directos ...,6/16 p,8,Promedio
7,Atención sostenida visual (TMT-A),32 sg,95,Alto
8,Atención selectiva visual (Búsqueda de símbolos),29,13,Promedio
9,Atención dividida visual (Clave de números-WAIS),42,11,Promedio
10,Lenguaje,NaN,NaN,NaN
11,Denominación de imágenes (TB),14/14 p,95,Alto
12,Comprensión de órdenes (TB),16/16 p,95,Alto
13,Material Verbal Complejo (TB),9 de 9,95,Alto
14,Memoria Verbal Test de Aprendizaje de Rey,NaN,NaN,NaN
15,Evocación inmediata Lista A ensayo 1,3/16 p,3/16 p,Promedio
16,Recuerdo inmediato Lista A ensayo 5,7/16 p,7/16 p,Bajo
17,Recuerdo inmediato Lista B,2/16 p,2/16 p,Bajo
18,Recuerdo libre a corto plazo,6/16 p,6/16 p,Bajo
19,Recuerdo libre a largo plazo,6/16 p,6/16 p,Bajo
20,Reconocimiento,12/16 p,12/16 p,Promedio
21,Memoria visual,NaN,NaN,NaN
22,Evocación diferida (Figura compleja de Rey),30/36 p,95,Alto
23,Capacidad Visuoperceptiva,NaN,NaN,NaN
24,Matrices (WAIS-IV),12/26 p,11,Promedio
25,Imágenes superpuestas (TB),20/20,95,Alto
26,Praxis,NaN,NaN,NaN
27,Constructiva (Figura compleja de Rey),36/36 p,85,Alto
28,Ideomotora Gestos simbólicos a la imitación -d...,10 de 10,95,Alto
29,Ideomotora Gestos simbólicos a la imitación -i...,10 de 10,95,Alto
30,Funciones ejecutivas,NaN,NaN,NaN
31,Memoria de Trabajo (Dígitos inversos WAIS-IV),6/16 p,10,Promedio
32,Memoria de Trabajo (Dígitos secuenciales WAIS-IV),7/16 p,10,Promedio
33,Test de fluidez fonológica FAS F,7,25,Promedio
34,Test de fluidez fonológica FAS A,11,55,Promedio
35,Test de fluidez fonológica FAS S,7,25,Promedio
36,Stroop Palabra,73,30,Promedio
37,Stroop Color,55,45,Promedio
38,Stroop Interferencia,25,30,Promedio
39,Semejanzas (TB),7/10 p,60,Promedio
40,Comprensión -abstracción (TB),12/12 p,95,Alto
41,Matrices (WAIS-IV),12/26 p,11,Promedio
42,Atención alternante (TMT B),120 sg.,65,Promedio

In [431]:
#Funcion para limpiar los nombres de las columnas y dejarlas mas estandarizadas
def clean_value(cadena):
  #Se eliminan espacios, se pasan a minusculas, se reemplazan espacios por guiones bajos, se eliminan acentos y caracteres especiales
  cadena = str(cadena).strip().lower().replace(' ', '_').replace('-','').replace("á", "a").replace("é", "e").replace("í", "i").replace("ó", "o").replace("ú", "u").replace(".","").replace("(","").replace(")","")
  return cadena

In [432]:
# funcion para detectar el formato de la tabla basándose en palabras clave en columnas específicas
def detect_table_format(sheet, keywords=['espacio'], check_columns=[0, 1]):
    """
    Detecta el formato de la tabla basándose en palabras clave en columnas específicas.
    
    Parámetros:
    - sheet: DataFrame a analizar
    - keywords: lista de palabras clave a buscar
    - check_columns: índices de columnas a verificar (0=primera columna, 1=segunda columna)
    
    Retorna:
    - 0 si la palabra clave se encuentra en la primera columna
    - 1 si la palabra clave se encuentra en la segunda columna
    - 'no determinada' si no se encuentra en ninguna
    """
    
    for col_idx in check_columns:
        if col_idx < len(sheet.columns):
            # Vectorizar la búsqueda: convierte a string y aplica clean_value vectorizado
            col_data = sheet.iloc[:, col_idx].astype(str).str.lower().str.strip()
            
            # Aplicar transformaciones necesarias vectorizadas
            col_data_clean = col_data.str.replace(' ', '_', regex=False)
            col_data_clean = col_data_clean.str.replace('[áéíóú]', 
                lambda m: {'á':'a', 'é':'e', 'í':'i', 'ó':'o', 'ú':'u'}.get(m.group(0), m.group(0)), 
                regex=True)
            col_data_clean = col_data_clean.str.replace(r'[\-\.\(\)]', '', regex=True)
            
            # Verificar si alguna palabra clave existe en la columna
            pattern = '|'.join(keywords)
            if col_data_clean.str.contains(pattern, na=False, case=False).any():
                return col_idx
    
    return 'no determinada'

# Aplicar la detección a todas las hojas de manera vectorizada
type_of_table = {name: detect_table_format(sheet) for name, sheet in cleaned_sheets.items()}

In [433]:
print(f'Cantidad de datos tipo tabla 0: {list(type_of_table.values()).count(0)}')
print(f'Cantidad de datos tipo tabla 1: {list(type_of_table.values()).count(1)}')
# print(f'Cantidad de datos con formato no determinado: {list(type_of_table.values()).count("no determinada")}')
print(f'Cantidad total de datos procesados: {len(type_of_table)}')

Cantidad de datos tipo tabla 0: 36
Cantidad de datos tipo tabla 1: 81
Cantidad total de datos procesados: 125

In [434]:
#Funcion para extraer la clasificación DC y edad del nombre de la hoja
def extract_patient_info(sheet_name):
    """Extrae la clasificación DC y edad del nombre de la hoja"""
    if 'F06' in str(sheet_name).upper():
        #Deterioro cognitivo leve
        dc = 1
    elif 'F02' in str(sheet_name).upper():
        #Demencia
        dc = 2
    elif 'GC' in str(sheet_name).upper():
        #Grupo de control
        dc = 0
    else: 
        dc = 'No determinada'
    
    age = str(sheet_name).split('-')[-1].strip()
    return dc, age

#funcion para extraer los valores de features de una tabla
def extract_features_from_table(sheet, headers_col, value_col, features, headers_clean=None):
    """
    Extrae los valores de features de una tabla.
    
    Parámetros:
    - sheet: DataFrame de la tabla
    - headers_col: índice de la columna con headers
    - value_col: índice de la columna con valores
    - features: lista de features a buscar
    - headers_clean: diccionario precominado de headers limpios
    
    Retorna: diccionario con los valores encontrados
    """
    # Pre-procesar headers para limpiarlos
    if headers_clean is None:
        headers = sheet.iloc[:, headers_col].astype(str)
        headers_clean = headers.apply(clean_value)
    else:
        headers_clean = headers_clean
    
    result = {}
    
    # Crear un diccionario para búsqueda rápida: feature_clean -> índice de fila
    feature_to_idx = {}
    for feature in features:
        mask = headers_clean.str.contains(feature, case=False, na=False)
        if mask.any():
            feature_to_idx[feature] = headers_clean[mask].index[0]
    
    # Extraer los valores para cada feature
    for feature in features:
        if feature in feature_to_idx:
            idx = feature_to_idx[feature]
            result[feature] = sheet.iloc[idx, value_col]
        else:
            result[feature] = None
    
    return result

def search_values(data, features):
    """
    Busca y extrae los valores de features de todas las tablas,
    diferenciando entre tabla formato 0 y formato 1.
    """
    # Configuración de parámetros para cada formato de tabla
    table_configs = {
        0: {'headers_col': 0, 'value_col': 2, 'nivel_estudio': 0},
        1: {'headers_col': 1, 'value_col': 3, 'nivel_estudio': 1}
    }
    
    results = []
    
    # Procesar todas las hojas
    for sheet_name, sheet in data.items():
        table_format = type_of_table[sheet_name]
        
        # Ignorar si el formato no se pudo determinar
        if table_format == 'no determinada':
            continue
        
        config = table_configs[table_format]
        
        # Extraer información del paciente
        dc, age = extract_patient_info(sheet_name)
        
        # Pre-procesar headers una sola vez para esta tabla
        headers = sheet.iloc[:, config['headers_col']].astype(str)
        headers_clean = headers.apply(clean_value)
        
        # Extraer features
        features_dict = extract_features_from_table(
            sheet, 
            config['headers_col'], 
            config['value_col'], 
            features,
            headers_clean
        )
        
        # Construir registro del paciente
        patient_data = {
            'sheet_name': sheet_name,
            'nivel_estudio': config['nivel_estudio'],
            'dc': dc,
            'age': age,
            **features_dict
        }
        
        results.append(patient_data)
    
    # Convertir a DataFrame
    dataset_final = pd.DataFrame(results)
    return dataset_final

In [435]:
df = search_values(cleaned_sheets, features_tablas)
#enviar solo los formatos de tabla 0 con sus respectivas features
cleaned_sheets_tabla_0 = {name: sheet for name, sheet in cleaned_sheets.items() if type_of_table[name] == 0}
df_tabla_0 = search_values(cleaned_sheets_tabla_0, features_tabla_0)
cleaned_sheets_tabla_1 = {name: sheet for name, sheet in cleaned_sheets.items() if type_of_table[name] == 1}
df_tabla_1 = search_values(cleaned_sheets_tabla_1, features_tabla_1)

In [436]:
df_tabla_0

,sheet_name,nivel_estudio,dc,age,tiempo,persona,espacio,atencion_sostenida_auditiva,atencion_sostenida_visual,atencion_selectiva_visual,atencion_dividida_visual,denominacion,comprension_de_ordenes,material_verbal_complejo,evocacion_inmediata_lista_a,recuerdo_inmediato_lista_a,recuerdo_inmediato_lista_b,recuerdo_libre_a_corto_plazo,recuerdo_libre_a_largo_plazo,reconocimiento,evocacion_inmediata_lista_b,evocacion_diferida,imagenes_superpuesta,constructiva,ideomotora_gestos_simbolicos_a_la_orden_derecha,ideomotora_gestos_simbolicos_a_la_orden_izquierda,ideomotora_gestos_simbolicos_a_la_imitacion_derecha,ideomotora_gestos_simbolicos_a_la_imitacion_izquierda,memoria_de_trabajo_digitos_inversos,memoria_de_trabajo_digitos_secuenciales,test_de_fluidez_fonologica_fas_f,test_de_fluidez_fonologica_fas_a,test_de_fluidez_fonologica_fas_s,evocacion_categorial_semantica,semejanzas,matrices,comprension_abstraccion,atencion_alternante,stroop_a,stroop_b,stroop_c,stroop_palabra,stroop_colores,stroop_interferencia
0,GC1-60,0,0,60,NaN,NaN,NaN,6,NaN,9,8,95.0,95,30.0,3/16 p,7/16 p,6/16 p,7/16 p,6/16 p,12/16 p,None,NaN,95.0,NaN,95,None,None,None,7,6.0,None,None,None,NaN,10,8.0,95,NaN,NaN,NaN,NaN,NaN,None,NaN
1,GC2-62,0,0,62,95,95.0,95.0,14,60,9,11,95.0,95,95.0,6/16 p,9/16 p,4/16 p,5/16 p,8/16 p,15/16 p,None,75,95.0,85,95,95,None,None,12,11.0,None,None,None,None,70,13.0,70,85,NaN,NaN,25,45,None,35
2,F021-72,0,2,72,95,95.0,95.0,6,<5,7,6,95.0,95,95.0,2/16 p,5/16 p,2/16 p,2/16 p,3/16 p,15/16 p,None,5,95.0,<5,95,95,95,95,4,6.0,None,None,None,<5,95,NaN,<5,<5,NaN,NaN,<5,<5,None,<5
3,S2-F067-53,0,1,53,95,95.0,95.0,8,<5,5,4,95.0,5,95.0,2/16 p,9/16 p,4/16 p,7/16 p,6/16 p,8/16 p,None,40,95.0,15,95,95,95,95,7,5.0,None,None,None,10,5,NaN,20,<5,NaN,NaN,5,<5,None,<5
4,GC3-60,0,0,60,95,95.0,95.0,10,50,9,9,95.0,95,20.0,6/16 p,13/16 p,6/16 p,10/16 p,8/16 p,14/16 p,None,75,95.0,85,95,95,95,95,12,NaN,>95,75,80,>95,40,11.0,90,85,90.0,85.0,55,None,None,None
5,S3-F067-66,0,1,66,95,95.0,95.0,11,<20,11,5,95.0,95,10.0,1/16 p,9/16 p,4/16 p,7/16 p,6/16 p,11/16 p,None,5,95.0,55,95,95,95,95,7,NaN,55,40,25,30,90,NaN,95,45,5.0,15.0,15,None,None,None
6,GC4-72,0,0,72,5,95.0,95.0,8,95,13,11,95.0,95,95.0,3/16 p,7/16 p,2/16 p,6/16 p,6/16 p,12/16 p,None,95,95.0,85,None,None,95,95,10,10.0,25,55,25,None,60,11.0,95,65,NaN,NaN,45,30,None,30
7,GC5-62,0,0,62,95,95.0,95.0,8,95,10,10,95.0,<5,95.0,4/15 p,10/15 p,4/15 p,7/15 p,8/15 p,14/15 p,None,35,95.0,70,None,None,95,95,9,6.0,20,20,20,None,60,7.0,60,55,NaN,NaN,35,45,None,20
8,S4-F067-66,0,1,66,95,95.0,95.0,9,55,11,10,95.0,95,95.0,4/16 p,9/16 p,3/16 p,6/16 p,8/16 p,14/16 p,None,NaN,NaN,75,None,None,95,95,9,10.0,None,None,None,None,95,NaN,95,65,NaN,NaN,35,10,None,15
9,GC6-69,0,0,69,95,95.0,95.0,11,80,11,10,95.0,95,95.0,6/16 p,15/16 p,7/16 p,14/16 p,14/16 p,15/16 p,None,75,95.0,85,None,None,None,None,12,14.0,60,75,90,90,None,13.0,95,95,NaN,NaN,55,30,None,45
10,GC7-70,0,0,70,95,95.0,95.0,10,95,9,12,95.0,95,95.0,7/16 p,14/16 p,7/16 p,13/16 p,15/16 p,16/16 p,None,>95,95.0,85,None,None,None,None,10,14.0,20,65,<5,25,70,11.0,95,90,NaN,NaN,75,60,None,75
11,F022-71,0,2,71,95,95.0,95.0,8,60,10,10,95.0,<5,95.0,3/15 p,10/15 p,2/15 p,0/15 p,3/15 p,14/15 p,None,35,NaN,55,None,None,None,None,7,9.0,None,None,None,None,<5,1.0,<5,<5,NaN,NaN,10,45,None,10
12,GC13-74,0,0,74,95,95.0,95.0,11,None,12,11,95.0,None,NaN,5/15 p,11/15 p,5/15 p,5/15 p,4/15 p,14/15 p,None,50,NaN,None,None,None,None,None,10,9.0,None,None,None,None,95,14.0,None,None,65.0,50.0,None,None,None,40
13,S16-F067-60,0,1,60,95,95.0,95.0,8,None,8,11,NaN,None,95.0,3/15 p,7/15 p,3/15 p,7/15 p,6/15 p,11/15 p,None,None,NaN,None,None,None,None,None,6,5.0,None,None,None,None,70,NaN,None,50,NaN,NaN,45,40,None,15
14,GC14-67,0,0,67,95,95.0,95.0,14,None,13,11,NaN,None,NaN,4/15 p,9/15 p,3/15 p,9/15 p,6/15 p,13/15 p,None,None,NaN,None,None,None,None,None,13,12.0,None,None,None,None,50,10.0,None,75,NaN,NaN,75,80,None,75
15,S34-F067-71,0,1,71,95,95.0,95.0,10,85,9,12,95.0,95,95.0,4/15 p,6/15 p,3/15 p,2/15 p,3/15 p,8/15 p,None,5,NaN,85,None,None,None,None,9,13.0,75,45,75,None,70,NaN,20,35,NaN,NaN,55,80,None,30
16,F0222-64,0,2,64,5,95.0,5.0,4,<15,3,3,95.0,95,95.0,2/16 p,2/16 p,1/16 p,0/16 p,0/16 p,15/16 p,None,<5,NaN,5,95,95,95,None,7,5.0,<5,<5,10,None,10,NaN,10,<15,NaN,NaN,10,5,None,<5
17,S35-F067-67,0,1,67,95,95.0,95.0,9,75,10,13,95.0,<5,10.0,3/16 p,10/16 p,3/16 p,4/16 p,1/16 p,15/16 p,None,20,NaN,55,None,None,None,None,11,11.0,<5,80,60,None,30,10.0,95,55,NaN,NaN,65,>95,None,30
18,GC17-60,0,0,60,95,95.0,95.0,8,85,10,10,95.0,95,5.0,5/16 p,10/16 p,5/16 p,7/16 p,7/16 p,16/16 p,None,40,NaN,85,None,None,None,None,4,8.0,None,None,None,None,40,7.0,<5,75,NaN,NaN,55,45,None,55
19,S36-F067-51,0,1,51,95,95.0,95.0,6,>95,5,4,95.0,95,95.0,NaN,NaN,NaN,NaN,NaN,NaN,None,20,NaN,20,None,None,None,None,11,8.0,35,55,20,None,70,6.0,<5,65,NaN,NaN,35,20,None,30
20,S46-F067-66,0,1,66,95,95.0,95.0,8,55,9,10,95.0,95,NaN,4/15 p,8/15 p,4/15 p,5/15 p,5/15 p,13/15 p,None,55,NaN,55,None,None,None,None,7,9.0,75,65,70,None,None,NaN,<5,30,NaN,NaN,45,45,None,15
21,GC21-64,0,0,64,95,95.0,95.0,6,75,8,9,95.0,95,NaN,5/15 p,14/15 p,5/15 p,13/15 p,10/15 p,15/15 p,None,40,NaN,55,None,None,None,None,6,6.0,20,55,<5,None,30,NaN,80,55,NaN,NaN,35,35,None,15
22,GC22-53,0,0,53,95,95.0,95.0,14,80,11,10,NaN,None,NaN,7/16 p,15/16 p,5/16 p,14/16 p,15/16 p,15/16 p,None,60,NaN,85,None,None,None,None,12,12.0,None,None,None,None,95,11.0,80,75,NaN,NaN,40,35,None,40
23,GC23-61,0,0,61,95,95.0,95.0,10,95,9,11,95.0,95,95.0,5/15 p,10/15 p,1/15 p,10/15 p,10/15 p,13/15 p,None,75,NaN,70,None,None,None,None,11,14.0,90,90,45,None,95,11.0,95,95,NaN,NaN,30,45,None,40
24,GC24-52,0,0,52,>5,95.0,95.0,6,75,5,6,95.0,>5,95.0,4/16 p,6/16 p,5/16 p,4/16 p,4/16 p,5/16 p,None,35,95.0,85,None,95,95,95,5,5.0,None,None,None,None,30,6.0,10,35,NaN,NaN,15,20,None,20
25,S50-F067-55,0,1,55,95,95.0,95.0,9,85,10,10,95.0,95,95.0,4/16 p,7/16 p,5/16 p,7/16 p,7/16 p,11/16 p,None,40,95.0,45,None,95,95,95,6,6.0,None,None,None,None,50,8.0,95,95,NaN,NaN,75,60,None,45
26,GC25-61,0,0,61,95,95.0,95.0,19,>95,13,15,95.0,95,95.0,5/16 p,13/16 p,8/16 p,11/16 p,8/16 p,15/16 p,None,>95,95.0,85,None,None,None,None,14,14.0,None,None,None,None,95,13.0,95,>95,NaN,NaN,75,65,None,85
27,S51-F067-73,0,1,73,95,95.0,95.0,12,65,9,10,95.0,5,40.0,3/15 p,5/15 p,1/15 p,0/15 p,0/15 p,6/15 p,None,<5,95.0,60,None,None,None,None,10,11.0,55,70,80,None,95,10.0,70,70,NaN,NaN,45,35,None,45
28,S52-F067-78,0,1,78,95,95.0,95.0,9,<20,5,4,95.0,<5,95.0,4/16 p,7/16 p,3/16 p,0/16 p,3/16 p,11/16 p,None,20,10.0,5,<5,<5,<5,<5,9,9.0,<5,<5,15,55,80,8.0,70,No logrado,NaN,NaN,None,None,None,None
29,S53-F067-54,0,1,54,95,95.0,95.0,3,45,5,5,NaN,95,95.0,1/15 p,6/15 p,3/15 p,2/15 p,3/15 p,10/15 p,None,45,NaN,70,None,None,None,None,5,5.0,None,None,None,5,4,5.0,<5,<5,NaN,NaN,None,None,None,None
30,S54-F067-68,0,1,68,95,95.0,95.0,11,30,7,6,95.0,95,95.0,3/15 p,5/15 p,0/15 p,2/15 p,0/15 p,5/15 p,None,<5,95.0,85,None,None,None,None,15,10.0,None,None,None,20,<5,8.0,60,<5,45.0,10.0,<5,None,None,None
31,S55-F067-64,0,1,64,95,95.0,95.0,9,<5,9,7,95.0,95,95.0,5/16 p,9/16 p,5/16 p,7/16 p,7/16 p,12/16 p,None,30,95.0,55,None,None,None,None,12,10.0,None,None,None,80,95,9.0,95,<5,10.0,35.0,10,None,None,None
32,GC26-59,0,0,59,95,95.0,95.0,8,90,9,9,95.0,95,95.0,7/16 p,15/16 p,5/16 p,10/16 p,7/16 p,16/16 p,None,30,95.0,45,None,None,None,None,7,7.0,None,None,None,80,70,7.0,95,75,40.0,50.0,35,None,None,None
33,F0229-71,0,2,71,<5,95.0,95.0,12,45,6,10,95.0,<5,95.0,2/16 p,6/16 p,2/16 p,1/16 p,0/16 p,13/16 p,None,<5,95.0,85,95,95,95,95,12,8.0,None,None,None,80,30,8.0,10,40,45.0,30.0,30,None,None,None
34,S56-F067-73,0,1,73,95,95.0,95.0,15,45,12,9,95.0,95,95.0,3/15 p,10/15 p,3/15 p,6/15 p,8/15 p,14/15 p,None,10,95.0,<5,95,None,None,None,12,13.0,None,None,None,None,50,NaN,95,15,NaN,NaN,30,45,None,40
35,S57-F067-55,0,1,55,95,95.0,95.0,8,45,6,6,95.0,95,95.0,2/15 p,7/15 p,2/15 p,5/15 p,5/15 p,12/15 p,None,25,NaN,75,None,None,None,None,6,6.0,None,None,None,None,<5,NaN,<5,<15,NaN,NaN,10,10,None,15

In [437]:
print(f'Grupo de control: {len(df[df["dc"] == 0])} personas')
print(f'Grupo de deterioro cognitivo: {len(df[df["dc"] == 1])} personas')
print(f'Grupo con demencia: {len(df[df["dc"] == 2])} personas')
# print(f'Cantidad total de personas con deterioro no determinada: {len(df[df["dc"] == "No determinada"])} personas, nombre de las hojas: {df[df["dc"] == "No determinada"]["sheet_name"].tolist()}')

Grupo de control: 27 personas
Grupo de deterioro cognitivo: 58 personas
Grupo con demencia: 32 personas

In [438]:
df.sample(20)

,sheet_name,nivel_estudio,dc,age,tiempo,persona,espacio,atencion_sostenida_auditiva,atencion_dividida_visual,digitos_en_progresion,deteccion_visual,denominacion,material_verbal_complejo,semejanzas,evocacion_diferida,evocacion_figura_semicompleja,memoria_de_trabajo_digitos_inversos,retencion_digitos_regresion
40,GC13-74,0,0,74,95,95.0,95.0,11.0,11.0,NaN,NaN,95,None,95,50,NaN,10.0,NaN
38,S15-F067-74,1,1,74,10,10.0,10.0,NaN,NaN,13.0,5.0,95,95,None,None,NaN,NaN,5.0
67,S32-F067-60,1,1,60,11,11.0,11.0,NaN,NaN,10.0,4.0,None,95,90,None,4.0,NaN,9.0
23,S7-F067-76,1,1,76,3,11.0,11.0,NaN,NaN,4.0,4.0,5,5,5,None,4.0,NaN,6.0
0,S1-F067-58,1,1,58,1,11.0,1.0,NaN,NaN,3.0,6.0,95,95,60,None,10.0,NaN,6.0
10,GC6-69,0,0,69,95,95.0,95.0,11.0,10.0,NaN,NaN,95,95,None,75,NaN,12.0,NaN
21,GC10-65,1,0,65,10,10.0,10.0,NaN,NaN,9.0,15.0,95,95,95,None,9.0,NaN,11.0
70,S34-F067-71,0,1,71,95,95.0,95.0,10.0,12.0,NaN,NaN,95,95,70,5,NaN,9.0,NaN
4,S2-F067-53,0,1,53,95,95.0,95.0,8.0,4.0,NaN,NaN,95,95,5,40,NaN,7.0,NaN
19,GC8-80,1,0,80,11,11.0,11.0,NaN,NaN,13.0,14.0,95,40,95,None,11.0,NaN,13.0
63,S29-F067-82,1,1,82,1,1.0,1.0,NaN,NaN,10.0,9.0,95,95,None,None,4.0,NaN,13.0
15,F023-87,1,2,87,1,1.0,1.0,NaN,NaN,9.0,2.0,5,<5,<5,None,5.0,NaN,1.0
114,F0233-85,1,2,85,1,1.0,1.0,NaN,NaN,4.0,2.0,<5,95,None,None,4.0,NaN,11.0
88,S44-F067-69,1,1,69,11,11.0,11.0,NaN,NaN,7.0,10.0,95,95,<5,None,6.0,NaN,6.0
11,GC7-70,0,0,70,95,95.0,95.0,10.0,12.0,NaN,NaN,95,95,70,>95,NaN,10.0,NaN
95,GC23-61,0,0,61,95,95.0,95.0,10.0,11.0,NaN,NaN,95,95,95,75,NaN,11.0,NaN
59,F0218-77,1,2,77,1,10.0,10.0,NaN,NaN,13.0,7.0,95,95,50,None,6.0,NaN,5.0
8,GC5-62,0,0,62,95,95.0,95.0,8.0,10.0,NaN,NaN,95,95,60,35,NaN,9.0,NaN
31,F028-70,1,2,70,1,1.0,10.0,NaN,NaN,9.0,8.0,5,<5,<5,None,4.0,NaN,5.0
89,F0228-86,1,2,86,1,1.0,1.0,NaN,NaN,9.0,1.0,95,<5,50,None,4.0,NaN,5.0

In [439]:
df_tablas = df.copy()

In [440]:
df_tablas['atencion_sostenida_auditiva'] = df_tablas['atencion_sostenida_auditiva'].fillna(df_tablas['digitos_en_progresion'])
df_tablas['atencion_dividida_visual'] = df_tablas['atencion_dividida_visual'].fillna(df_tablas['deteccion_visual'])
# df_tablas['comprension_de_ordenes'] = df_tablas['comprension_de_ordenes'].fillna(df_tablas['comprension_ejecucion_de_ordenes'])
df_tablas['evocacion_diferida'] = df_tablas['evocacion_diferida'].fillna(df_tablas['evocacion_figura_semicompleja'])
# df_tablas['constructiva'] = df_tablas['constructiva'].fillna(df_tablas['copia_de_figura_compleja'])
df_tablas['retencion_digitos_regresion'] = df_tablas['retencion_digitos_regresion'].fillna(df_tablas['memoria_de_trabajo_digitos_inversos'])


df_tablas.drop(columns=['digitos_en_progresion'], inplace=True)
df_tablas.drop(columns=['deteccion_visual'], inplace=True)
# df_tablas.drop(columns=['comprension_ejecucion_de_ordenes'], inplace=True)
df_tablas.drop(columns=['evocacion_figura_semicompleja'], inplace=True)
# df_tablas.drop(columns=['copia_de_figura_compleja'], inplace=True)
df_tablas.drop(columns=['memoria_de_trabajo_digitos_inversos'], inplace=True)

In [441]:
df_tablas.sample(5)

,sheet_name,nivel_estudio,dc,age,tiempo,persona,espacio,atencion_sostenida_auditiva,atencion_dividida_visual,denominacion,material_verbal_complejo,semejanzas,evocacion_diferida,retencion_digitos_regresion
116,F0234-87,1,2,87,1,1.0,1.0,7.0,4.0,5,5,60,3.0,9.0
22,F026-92,1,2,92,1,10.0,10.0,12.0,3.0,95,95,5,4.0,8.0
36,F0210-77,1,2,77,1,1.0,11.0,5.0,11.0,95,30,50,NaN,11.0
9,S4-F067-66,0,1,66,95,95.0,95.0,9.0,10.0,95,95,95,NaN,9.0
58,F0217-88,1,2,88,1,11.0,11.0,16.0,5.0,95,5,5,4.0,13.0

In [442]:
df_tablas.columns

Index(['sheet_name', 'nivel_estudio', 'dc', 'age', 'tiempo', 'persona',
       'espacio', 'atencion_sostenida_auditiva', 'atencion_dividida_visual',
       'denominacion', 'material_verbal_complejo', 'semejanzas',
       'evocacion_diferida', 'retencion_digitos_regresion'],
      dtype='object')

In [443]:
df_tablas.isna().sum()

sheet_name                      0
nivel_estudio                   0
dc                              0
age                             0
tiempo                          4
persona                         4
espacio                         4
atencion_sostenida_auditiva     3
atencion_dividida_visual        6
denominacion                   10
material_verbal_complejo       15
semejanzas                     11
evocacion_diferida             14
retencion_digitos_regresion     4
dtype: int64

In [444]:
print(df_tabla_0.shape)
df_tabla_0.isna().sum()

(36, 44)

sheet_name                                                0
nivel_estudio                                             0
dc                                                        0
age                                                       0
tiempo                                                    1
persona                                                   1
espacio                                                   1
atencion_sostenida_auditiva                               0
atencion_sostenida_visual                                 4
atencion_selectiva_visual                                 0
atencion_dividida_visual                                  0
denominacion                                              4
comprension_de_ordenes                                    4
material_verbal_complejo                                  5
evocacion_inmediata_lista_a                               1
recuerdo_inmediato_lista_a                                1
recuerdo_inmediato_lista_b                                1
recuerdo_libre_a_corto_plazo                              1
recuerdo_libre_a_largo_plazo                              1
reconocimiento                                            1
evocacion_inmediata_lista_b                              36
evocacion_diferida                                        4
imagenes_superpuesta                                     16
constructiva                                              4
ideomotora_gestos_simbolicos_a_la_orden_derecha          26
ideomotora_gestos_simbolicos_a_la_orden_izquierda        26
ideomotora_gestos_simbolicos_a_la_imitacion_derecha      24
ideomotora_gestos_simbolicos_a_la_imitacion_izquierda    25
memoria_de_trabajo_digitos_inversos                       0
memoria_de_trabajo_digitos_secuenciales                   2
test_de_fluidez_fonologica_fas_f                         21
test_de_fluidez_fonologica_fas_a                         21
test_de_fluidez_fonologica_fas_s                         21
evocacion_categorial_semantica                           24
semejanzas                                                2
matrices                                                 11
comprension_abstraccion                                   3
atencion_alternante                                       2
stroop_a                                                 29
stroop_b                                                 29
stroop_c                                                  4
stroop_palabra                                           10
stroop_colores                                           36
stroop_interferencia                                      9
dtype: int64

In [445]:
print(df_tabla_1.shape)
df_tabla_1.isna().sum()

(81, 34)

sheet_name                            0
nivel_estudio                         0
dc                                    0
age                                   0
tiempo                                3
persona                               3
espacio                               3
digitos_en_progresion                 3
cubos_progresion                     53
deteccion_visual                      6
deteccion_digitos_total              60
series_sucesivas                      3
denominacion                          6
semejanzas                            9
lectura_de_palabras                  71
material_verbal_complejo             10
comprension_ejecucion_de_ordenes     48
curva_de_memoria_volumen_promedio     7
memoria_verbal_espontanea_total       7
memoria_verbal_claves_total           7
memoria_verbal_reconocimiento         7
memoria_logica_promedio_historias    30
caras_codificacion                   15
reconocimiento_caras                 14
evocacion_figura_semicompleja        10
imagenes_superpuesta                 46
copia_de_figura_compleja             39
gestos_simbolicos                    24
imitacion_de_posturas                50
fluidez_verbal_semantica              3
fluidez_verbal_fonologica             3
fluidez_no_verbal                     6
retencion_digitos_regresion           4
cubos_regresion                      39
dtype: int64

In [446]:
# menor a 5 alteracion Alteración Severa
# 5 a 24 bajo   
# 25 a 85 promedio
# 85 a 100 Alto

#Alteracion severa - 1,2,3
#bajo - 4,5,6
#promedio - 7-13
#Alto - 14-18