In [33]:
import pandas as pd
from dotenv import dotenv_values
import requests
from io import BytesIO

In [34]:
config = dotenv_values(dotenv_path=".env")

# Pipeline

In [35]:
url = f"https://{config['GITHUB_TOKEN']}@raw.githubusercontent.com/Nicolasg2c/dc_model_ts/main/common/data/EJEMPLO%20MUESTRA.xlsx"

In [36]:
url = "https://raw.githubusercontent.com/Nicolasg2c/dc_model_ts/main/common/data/EJEMPLO%20MUESTRA.xlsx"
headers = {"Authorization": f"Bearer {config['GITHUB_TOKEN']}"}
r = requests.get(url, headers=headers, timeout=30)
r.raise_for_status()  # Check if the request was successful

df = pd.read_excel(BytesIO(r.content), header=None, sheet_name=None, engine="openpyxl")

In [37]:
df

{'001-DCL-H53':                                                     0           1  \
 0                                                 NaN         NaN
 1                                                 NaN         NaN
 2                                                 NaN         NaN
 3                    FUNCIÓN EVALUADA (TEST EMPLEADO)  P. Directa
 4                                 Prueba de tamizaje          NaN
 5                                                MoCA           9
 6                                  Pruebas de validez         NaN
 7            Reconocimiento inmediato ensayo 1 (TOMM)      13/50
 8            Reconocimiento inmediato ensayo 2 (TOMM)       17/50
 9             Reconocimiento diferido ensayo 3 (TOMM)       15/50
 10                                                NaN         NaN
 11                                        Orientación         NaN
 12                        Orientación en persona (TB)      7 de 7
 13                        Orientación en espacio (TB)      5 de 5
 14                         Orientación en tiempo (TB)     12/23 p
 15                                                NaN         NaN
 16  Capacidad atencional y velocidad de procesamiento         NaN
 17  Atención sostenida auditiva (Dígitos directos ...      2/16 p
 18                  Atención sostenida visual (TMT-A)    196 sg.
 19  Atención selectiva visual (Búsqueda de símbolo...           6
 20  Atención dividida visual (Clave de números-WAI...           4
 21                                                NaN         NaN
 22                                           Lenguaje         NaN
 23                      Denominación de imágenes (TB)       13/14
 24                        Comprensión de órdenes (TB)       13/16
 25                      Material Verbal Complejo (TB)       6/9 p
 26                                                NaN         NaN
 27             California Verbal Learning Test (CVLT)         NaN
 28               Evocación inmediata Lista A ensayo 1      2/15 p
 29                Recuerdo inmediato Lista A ensayo 5      4/15 p
 30                         Recuerdo inmediato Lista B      2/15 p
 31                       Recuerdo libre a corto plazo      1/15 p
 32                       Recuerdo libre a largo plazo      0/15 p
 33                                     Reconocimiento      5/15 p
 34                                                NaN         NaN
 35                                     Memoria visual         NaN
 36        Evocación diferida (Figura compleja de Rey)      3/36 p
 37           Reconocimiento inmediato ensayo 2 (TOMM)       17/50
 38            Reconocimiento diferido ensayo 3 (TOMM)       15/50
 39                                                NaN         NaN
 40                          Capacidad Visuoperceptiva         NaN
 41                         Imágenes superpuestas (TB)       19/20
 42                                                NaN         NaN
 43                                             Praxis         NaN
 44              Constructiva (Figura compleja de Rey)     25/36 p
 45  Ideomotora Gestos simbólicos a la orden- derec...     10/10 p
 46  Ideomotora Gestos simbólicos a la orden- izqui...     10/10 p
 47  Ideomotora Gestos simbólicos a la imitación -d...     10/10 p
 48  Ideomotora Gestos simbólicos a la imitación -i...     10/10 p
 49                                                NaN         NaN
 50                               Funciones ejecutivas         NaN
 51      Memoria de Trabajo (Dígitos inversos WAIS-IV)      4/16 p
 52  Memoria de Trabajo (Dígitos secuenciales WAIS-IV)      4/16 p
 53                   Test de fluidez fonológica FAS-F           1
 54                   Test de fluidez fonológica FAS-A           2
 55                   Test de fluidez fonológica FAS-S           3
 56          Evocación categorial semántica (animales)           6
 57                                    Semejanzas (TB)      4/12 p
 58                      Comprensión -abstracción (TB)      0/12 p
 59                        Atención alternante (TMT B)  No logrado

                          2                    3
 0                      NaN                  NaN
 1                      NaN                  NaN
 2                      NaN                  NaN
 3   Percentil o P. Directa        Clasificación
 4                      NaN                  NaN
 5                        9  Deterioro Cognitivo
 6                      NaN                  NaN
 7                       <5                 Bajo
 8                       <5                 Bajo
 9                       <5                 Bajo
 10                     NaN                  NaN
 11                     NaN                  NaN
 12                      95             Promedio
 13                      95             Promedio
 14                      <5              Déficit
 15                     NaN                  NaN
 16                     NaN                  NaN
 17                       1                 Bajo
 18                      <5                 Bajo
 19                       4                 Bajo
 20                       2                 Bajo
 21                     NaN                  NaN
 22                     NaN                  NaN
 23                      10                 Bajo
 24                       5              Déficit
 25                      10                 Bajo
 26                     NaN                  NaN
 27                     NaN                  NaN
 28                  2/15 p                 Bajo
 29                  4/15 p                 Bajo
 30                  2/15 p                 Bajo
 31                  1/15 p                 Bajo
 32                  0/15 p                 Bajo
 33                  5/15 p                 Bajo
 34                     NaN                  NaN
 35                     NaN                  NaN
 36                       5                 Bajo
 37                      <5                 Bajo
 38                      <5                 Bajo
 39                     NaN                  NaN
 40                     NaN                  NaN
 41                      80             Promedio
 42                     NaN                  NaN
 43                     NaN                  NaN
 44                      25             Promedio
 45                      95             Promedio
 46                      95             Promedio
 47                      95             Promedio
 48                      95             Promedio
 49                     NaN                  NaN
 50                     NaN                  NaN
 51                       5                 Bajo
 52                       5                 Bajo
 53                      <5                 Bajo
 54                      <5                 Bajo
 55                      <5                 Bajo
 56                      <5                 Bajo
 57                      20             Promedio
 58                      <5                 Bajo
 59              No logrado           No logrado  ,
 '002-NORMAL-M62':                                                     0           1  \
 0                                                 NaN         NaN
 1                                                 NaN         NaN
 2                                                 NaN         NaN
 3                    FUNCIÓN EVALUADA (TEST EMPLEADO)  P. Directa
 4                                 Prueba de tamizaje          NaN
 5                                                MoCA          24
 6                                                 NaN         NaN
 7                                         Orientación         NaN
 8                         Orientación en persona (TB)      7 de 7
 9                         Orientación en espacio (TB)      5 de 5
 10                         Orientación en tiempo (TB)     23/23 p
 11                                                NaN         NaN
 12  Capacidad atencional y velocidad de procesamiento         NaN
 13  Atención sostenida auditiva (Dígitos directos ...     11/16 p
 14                  Atención sostenida visual (TMT-A)     62 sg.
 15  Atención selectiva visual (Búsqueda de símbolo...          17
 16  Atención dividida visual (Clave de números-WAI...          56
 17                                                NaN         NaN
 18                                           Lenguaje         NaN
 19                      Denominación de imágenes (TB)       14/14
 20                        Comprensión de órdenes (TB)       16/16
 21                      Material Verbal Complejo (TB)       9/9 p
 22                                                NaN         NaN
 23             California Verbal Learning Test (CVLT)         NaN
 24               Evocación inmediata Lista A ensayo 1      6/16 p
 25                Recuerdo inmediato Lista A ensayo 5      9/16 p
 26                         Recuerdo inmediato Lista B      4/16 p
 27                       Recuerdo libre a corto plazo      5/16 p
 28                       Recuerdo libre a largo plazo      8/16 p
 29               Recuerdo libre con claves semánticas      8/16 p
 30                                     Reconocimiento     15/16 p
 31                                                NaN         NaN
 32                                     Memoria visual         NaN
 33        Evocación diferida (Figura compleja de Rey)     22/36 p
 34                                                NaN         NaN
 35                          Capacidad Visuoperceptiva         NaN
 36                         Imágenes superpuestas (TB)       20/20
 37                                                NaN         NaN
 38                                             Praxis         NaN
 39              Constructiva (Figura compleja de Rey)     36/36 p
 40  Ideomotora Gestos simbólicos a la orden- derec...     10/10 p
 41  Ideomotora Gestos simbólicos a la orden- izqui...     10/10 p
 42                                                NaN         NaN
 43                               Funciones ejecutivas         NaN
 44      Memoria de Trabajo (Dígitos inversos WAIS-IV)      9/16 p
 45  Memoria de Trabajo (Dígitos secuenciales WAIS-IV)      8/16 p
 46                                     Stroop Palabra          80
 47                                       Stroop Color          44
 48                              Stroop Interferencia           26
 49                                 Matrices (WAIS-IV)     19/26 p
 50                                    Semejanzas (TB)     11/12 p
 51                               Aritmética (WAIS-IV)     16/26 p
 52                      Comprensión -abstracción (TB)     10/12 p
 53                       Atención alternante (TMT B)       80 sg.

                          2              3
 0                      NaN            NaN
 1                      NaN            NaN
 2                      NaN            NaN
 3   Percentil o P. Directa  Clasificación
 4                      NaN            NaN
 5                       24     Normalidad
 6                      NaN            NaN
 7                      NaN            NaN
 8                       95           Alto
 9                       95           Alto
 10                      95           Alto
 11                     NaN            NaN
 12                     NaN            NaN
 13                      14       Promedio
 14                      60       Promedio
 15                       9       Promedio
 16                      11       Promedio
 17                     NaN            NaN
 18                     NaN            NaN
 19                      95           Alto
 20                      95           Alto
 21                      95           Alto
 22                     NaN            NaN
 23                     NaN            NaN
 24                  6/16 p       Promedio
 25                  9/16 p           Bajo
 26                  4/16 p       Promedio
 27                  5/16 p           Bajo
 28                  8/16 p           Bajo
 29                  8/16 p           Bajo
 30                 15/16 p       Promedio
 31                     NaN            NaN
 32                     NaN            NaN
 33                      75       Promedio
 34                     NaN            NaN
 35                     NaN            NaN
 36                      95           Alto
 37                     NaN            NaN
 38                     NaN            NaN
 39                      85           Alto
 40                      95           Alto
 41                      95           Alto
 42                     NaN            NaN
 43                     NaN            NaN
 44                      12       Promedio
 45                      11       Promedio
 46                      45       Promedio
 47                      25       Promedio
 48                      35       Promedio
 49                      13       Promedio
 50                      70       Promedio
 51                      13       Promedio
 52                      70       Promedio
 53                      85           Alto  ,
 '003-DCL-H72':                                             0           1  \
 0                                         NaN         NaN
 1                                         NaN         NaN
 2                                         NaN         NaN
 3            FUNCIÓN EVALUADA (TEST EMPLEADO)  P. Directa
 4                         Prueba de tamizaje          NaN
 ..                                        ...         ...
 57          Stroop Interferencia * 5 errores*           5
 58  Evocación categorial semántica (animales)           4
 59                            Semejanzas (TB)     10/10 p
 60              Comprensión -abstracción (TB)      2/12 p
 61               Atención alternante (TMT B)   No logrado

                          2              3
 0                      NaN            NaN
 1                      NaN            NaN
 2                      NaN            NaN
 3   Percentil o P. Directa  Clasificación
 4                      NaN            NaN
 ..                     ...            ...
 57                      <5        Déficit
 58                      <5        Déficit
 59                      95           Alto
 60                      <5        Déficit
 61                      <5        Déficit

 [62 rows x 4 columns],
 '004-DCL-M62':                                                     0           1  \
 0                                                 NaN         NaN
 1                                                 NaN         NaN
 2                                                 NaN         NaN
 3                    FUNCIÓN EVALUADA (TEST EMPLEADO)  P. Directa
 4                                                 NaN         NaN
 5                                         Orientación         NaN
 6                         Orientación en persona (TB)      7 de 7
 7                         Orientación en espacio (TB)      5 de 5
 8                          Orientación en tiempo (TB)     23/23 p
 9                                                 NaN         NaN
 10  Capacidad atencional y velocidad de procesamiento         NaN
 11  Atención sostenida auditiva (Dígitos directos ...      6/16 p
 12                  Atención sostenida visual (TMT-A)    200 sg.
 13  Atención selectiva visual (Búsqueda de símbolo...           8
 14  Atención dividida visual (Clave de números-WAI...          11
 15                                                NaN         NaN
 16                                           Lenguaje         NaN
 17                      Denominación de imágenes (TB)       14/14
 18                        Comprensión de órdenes (TB)       13/16
 19                      Material Verbal Complejo (TB)       9/9 p
 20                                                NaN         NaN
 21             California Verbal Learning Test (CVLT)         NaN
 22               Evocación inmediata Lista A ensayo 1      2/16 p
 23                Recuerdo inmediato Lista A ensayo 5      9/16 p
 24                         Recuerdo inmediato Lista B      4/16 p
 25                       Recuerdo libre a corto plazo      7/16 p
 26                       Recuerdo libre a largo plazo      6/16 p
 27               Recuerdo libre con claves semánticas      6/16 p
 28         Reconocimiento*sin falsos reconocimientos*      8/16 p
 29                                                NaN         NaN
 30                                     Memoria visual         NaN
 31        Evocación diferida (Figura compleja de Rey)     12/36 p
 32                                                NaN         NaN
 33                          Capacidad Visuoperceptiva         NaN
 34                         Imágenes superpuestas (TB)       20/20
 35                                                NaN         NaN
 36                                             Praxis         NaN
 37              Constructiva (Figura compleja de Rey)     21/36 p
 38  Ideomotora Gestos simbólicos a la orden- derec...     10/10 p
 39  Ideomotora Gestos simbólicos a la orden- izqui...     10/10 p
 40  Ideomotora Gestos simbólicos a la imitación -d...     10/10 p
 41  Ideomotora Gestos simbólicos a la imitación -i...     10/10 p
 42                                                NaN         NaN
 43                               Funciones ejecutivas         NaN
 44      Memoria de Trabajo (Dígitos inversos WAIS-IV)      5/16 p
 45  Memoria de Trabajo (Dígitos secuenciales WAIS-IV)      3/16 p
 46                   Test de fluidez fonológica FAS-F           6
 47                   Test de fluidez fonológica FAS-A           5
 48                   Test de fluidez fonológica FAS-S           5
 49                                     Stroop Palabra          30
 50                                       Stroop Color          30
 51                  Stroop Interferencia * 3 errores*          10
 52          Evocación categorial semántica (animales)          10
 53                                    Semejanzas (TB)      3/12 p
 54                      Comprensión -abstracción (TB)      3/12 p
 55            Atención alternante (TMT B) *6 errores*     420 seg

                          2              3
 0                      NaN            NaN
 1                      NaN            NaN
 2                      NaN            NaN
 3   Percentil o P. Directa  Clasificación
 4                      NaN            NaN
 5                      NaN            NaN
 6                       95           Alto
 7                       95           Alto
 8                       95           Alto
 9                      NaN            NaN
 10                     NaN            NaN
 11                       8       Promedio
 12                      <5        Déficit
 13                       5           Bajo
 14                       4           Bajo
 15                     NaN            NaN
 16                     NaN            NaN
 17                      95           Alto
 18                       5           Bajo
 19                      95           Alto
 20                     NaN            NaN
 21                     NaN            NaN
 22                  2/16 p           Bajo
 23                  9/16 p           Bajo
 24                  4/16 p           Bajo
 25                  7/16 p           Bajo
 26                  6/16 p           Bajo
 27                  6/16 p           Bajo
 28                  8/16 p           Bajo
 29                     NaN            NaN
 30                     NaN            NaN
 31                      40       Promedio
 32                     NaN            NaN
 33                     NaN            NaN
 34                      95           Alto
 35                     NaN            NaN
 36                     NaN            NaN
 37                      15           Bajo
 38                      95           Alto

In [38]:
cleaned_sheets = {}
for name, sheet in df.items():
    sheet = sheet.dropna(how="all")       # eliminar filas vacías
    sheet.columns = sheet.iloc[0]         # primera fila como headers
    sheet = sheet.drop(sheet.index[0])    # eliminar fila usada como header
    sheet = sheet.reset_index(drop=True)
    cleaned_sheets[name] = sheet

In [39]:
cleaned_sheets.keys()

dict_keys(['001-DCL-H53', '002-NORMAL-M62', '003-DCL-H72', '004-DCL-M62', '005-NORMAL-M60', '006-DCL-M66', '007-NORMAL-H72', '008-NORMAL-M62', '009-NORMAL-M69', '010-NORMAL-H60', '011-DCM-H71', '012-DCL-H74', '013-DCM-M87', '014-DCL-M75', '015-DCM-H62'])

In [40]:
#MAPA DE VALORES COGNITIVOS

dominios_cognitivos = {
        "prueba_validez": [
            'reconocimiento_inmediato_ensayo_1', 'reconocimiento_inmediato_ensayo_2', 'reconocimiento_diferido_ensayo_3'
            ],

        "orientacion": [
            'orientacion_persona',
            'orientacion_espacio',
            'orientacion_tiempo'
            ],

        "cap_atencional": [
            'vel_procesamiento_atencion_sostenida_auditiva','vel_procesamiento_atencion_sostenida_visual','vel_procesamiento_atencion_selectiva_visual','vel_procesamiento_atencion_dividida_visual'
            ],

        "lenguaje": [
            'denominacion_imagenes',
            'comprension_ordenes',
            'material_verbal_complejo',
            'lectura_palabras'
            ],

        "cvlt": [
            'evocacion_inmediata_lista_a',
            'recuerdo_inmediato_lista_a',
            'recuerdo_inmediato_lista_b',
            'recuerdo_libre_corto_plazo',
            'recuerdo_libre_largo_plazo',
            'recuerdo_libre_largo_plazo_clave',
            'reconocimiento'
            ],

        "memoria_visual": [
            'visual_evocacion_diferida',
            'visual_reconocimiento_inmediato',
            'visual_reconocimiento_diferido'
            ],

        "capacidad_visuoperceptiva": ['imagenes_superpuesta'],

        "praxis": [
            'constructiva',
            'gestos_ideomotora_simbolicos_orden_derecha',
            'gestos_ideomotora_simbolicos_orden_izquierda',
            'gestos_ideomotora_simbolicos_imitacion_derecha','gestos_ideomotora_simbolicos_imitacion_izquierda'
            ],

        "funcionalidades_ejecutivas": [
            'memoria_de_trabajo_digitos_inversos',
            'memoria_de_trabajo_digitos_secuenciales','test_fluidez_de_fonologica_FAS_F',
            'test_fluidez_de_fonologica_FAS_A',
            'test_fluidez_de_fonologica_FAS_S',
            'evocacion_categorial_semantica',
            'semejanzas',
            'matrices',
            'comprension_abstraccion',
            'atencion_alternante',
            'stroop_A',
            'stroop_b',
            'stroop_c'
            ]
}

In [41]:
test = [
    'orientacion_en_persona',
    'orientacion_en_espacio',
    'orientacion_en_tiempo',

    'atencion_sostenida_auditiva',
    'atencion_sostenida_visual',
    'atencion_selectiva_visual',
    'atencion_dividida_visual',

    'denominacion_de_imagenes',
    'comprension_de_ordenes',
    'material_verbal_complejo',

    'evocacion_inmediata_lista_a',
    'recuerdo_inmediato_lista_a',
    'recuerdo_inmediato_lista_b',
    'recuerdo_libre_a_corto_plazo',
    'recuerdo_libre_a_largo_plazo',
    'recuerdo_libre_a_largo_plazo_clave',
    'reconocimiento',

    'evocacion_diferida',
    'reconocimiento_inmediato_ensayo_2',
    'reconocimiento_diferido_ensayo_3',

    'imagenes_superpuesta',

    'constructiva',
    'ideomotora_gestos_simbolicos_a_la_orden_derecha',
    'ideomotora_gestos_simbolicos_a_la_orden_izquierda',
    'ideomotora_gestos_simbolicos_a_la_imitacion_derecha',
    'ideomotora_gestos_simbolicos_a_la_imitacion_izquierda',

    'memoria_de_trabajo_digitos_inversos',
    'memoria_de_trabajo_digitos_secuenciales',
    'test_de_fluidez_fonologica_fas_f',
    'test_de_fluidez_fonologica_fas_a',
    'test_de_fluidez_fonologica_fas_s',
    'evocacion_categorial_semantica',
    'semejanzas',
    'matrices',
    'comprension_abstraccion',
    'atencion_alternante',
    'stroop_a',
    'stroop_b',
    'stroop_c',
    'stroop_palabra',
    'stroop_colores',
    'stroop_interferencia',
  ]

In [42]:
cleaned_sheets['015-DCM-H62']

,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alto: 14 a 19 puntos,NaN,Alto: 80 a 95 puntos
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Promedio: 7 a13 puntos,NaN,Promedio: 30 a 70 puntos
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alteración leve- moderado: 4 a 6 puntos,NaN,Bajo: 10 a 20 puntos
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Alteración severa: 1 a 3 puntos,NaN,Déficit: <5 puntos
3,Dominio-Neuropsi Atención y Memoria- Test de B...,NaN,Puntuación obtenida,Puntuación normalizada,Interpretación,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Orientación,Tiempo,2/4 p,1,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Espacio,1/2 p,1,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Persona,1/1 p,11,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Atención y concentración,Dígitos en progresión,0/9 p,1,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Cubos progresión,0/9 p,2,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Detección visual,7/24 p,5,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Series sucesivas,0/3 p,4,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Memoria - Codificación,Curva de Memoria Volumen Promedio,3/12 p,4,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Memoria Verbal Espontánea total,3/12 p,8,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,Memoria Verbal Claves Total,3/12 p,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Memoria Verbal Reconocimiento Total,3/12 p,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,Memoria Lógica Promedio Historias,2/16 p,2,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Memoria Lógica Promedio Historias,0/16 p,1,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Memoria visual,Caras codificación,4/4 p,11,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,Reconocimiento Caras,1/2 p,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,TOMM ensayo 1 *percentil*,27/50,<5,Déficit,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,TOMM ensayo 2 *percentil*,29/50,<5,Déficit,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,Evocación figura compleja de Rey *percentil*,5/36 p,10,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Gnosias,Imágenes superpuestas (TB),10/20 p,<5,Déficit,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Lenguaje,Denominación (TB),14/14 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,Repetición verbal palabras (TB),10/10 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Praxias,Gestos simbólicos orden (TB),10/10 p,95,Alto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,Praxias construccionales-orden (TB),6/18 p,<5,Déficit,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Figura compleja de Rey,13/36 p,5,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,"Funciones ejecutivas, conceptuales y motoras",Formación categorías,4/25 p,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,Fluidez verbal semántica,7,3,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,Fluidez verbal fonológica,8,7,Promedio,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,Fluidez no verbal,0,4,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,Retención dígitos regresión,2/8 p,6,Alteración Leve,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,Cubos Regresión,0/9 p,1,Alteración severa,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,[1]Perfil general de ejecución. Rango de edad:...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
def clean_value(cadena):
  cadena = cadena.strip().lower().replace(' ', '_').replace('-','').replace("á", "a").replace("é", "e").replace("í", "i").replace("ó", "o").replace("ú", "u").replace(".","").replace("(","").replace(")","")
  return cadena

In [44]:
#FUNCION PARA LIMPIAR KEYS
def clean_keys(df):
  headers = {}
  for header in df.keys():
    new_header = clean_value(header)
    headers[header]=new_header
  df = df.rename(columns = headers)
  return df

In [52]:
def search_values(df_raw, df_clean, patient_id):
  df_raw = clean_keys(df_raw)
  patient_data = {}
  for column in df_clean:
    # print(f'buscando el valor de la columna {column}')
    column_keys = df_raw[df_raw.columns[0]]
    column_keys_clean = column_keys.apply(clean_value)
    filter = column_keys_clean.str.contains(column, case=False,na=False)
    if(len(df_raw[filter].index) > 0):
      idx = df_raw[filter].index[0]
      finding_values = df_raw.iloc[idx, df_raw.columns.get_loc("percentil_o_p_directa")]
      # print(f'valor: {finding_values}')
      patient_data[column] = finding_values
    else:
      patient_data[column] = None
  return patient_data

In [46]:
pd.set_option("display.max_columns", None)  # mostrar todas las columnas

In [47]:
patients_info = []
for i, patient in enumerate(cleaned_sheets):
  print(patient)
  try:
    patient_data = search_values(cleaned_sheets[patient], test, i)
    patient_data['sexo'] = 'M' if 'H' in patient else 'F'
    patient_data['DC'] = 0 if 'NORMAL' in patient else 1 if 'DCL' in patient else 2
    patients_info.append(patient_data)
  except Exception as e:
    print(f'ocurrio un error {e}')

001-DCL-H53
002-NORMAL-M62
003-DCL-H72
004-DCL-M62
005-NORMAL-M60
006-DCL-M66
007-NORMAL-H72
008-NORMAL-M62
009-NORMAL-M69
010-NORMAL-H60
011-DCM-H71
012-DCL-H74
ocurrio un error 'float' object has no attribute 'strip'
013-DCM-M87
ocurrio un error 'float' object has no attribute 'strip'
014-DCL-M75
ocurrio un error 'float' object has no attribute 'strip'
015-DCM-H62
ocurrio un error 'float' object has no attribute 'strip'

In [48]:
patients_df = pd.DataFrame(patients_info)
patients_df

,orientacion_en_persona,orientacion_en_espacio,orientacion_en_tiempo,atencion_sostenida_auditiva,atencion_sostenida_visual,atencion_selectiva_visual,atencion_dividida_visual,denominacion_de_imagenes,comprension_de_ordenes,material_verbal_complejo,evocacion_inmediata_lista_a,recuerdo_inmediato_lista_a,recuerdo_inmediato_lista_b,recuerdo_libre_a_corto_plazo,recuerdo_libre_a_largo_plazo,recuerdo_libre_a_largo_plazo_clave,reconocimiento,evocacion_diferida,reconocimiento_inmediato_ensayo_2,reconocimiento_diferido_ensayo_3,imagenes_superpuesta,constructiva,ideomotora_gestos_simbolicos_a_la_orden_derecha,ideomotora_gestos_simbolicos_a_la_orden_izquierda,ideomotora_gestos_simbolicos_a_la_imitacion_derecha,ideomotora_gestos_simbolicos_a_la_imitacion_izquierda,memoria_de_trabajo_digitos_inversos,memoria_de_trabajo_digitos_secuenciales,test_de_fluidez_fonologica_fas_f,test_de_fluidez_fonologica_fas_a,test_de_fluidez_fonologica_fas_s,evocacion_categorial_semantica,semejanzas,matrices,comprension_abstraccion,atencion_alternante,stroop_a,stroop_b,stroop_c,stroop_palabra,stroop_colores,stroop_interferencia,sexo,DC
0,95,95,<5,1,<5,4,2,10.0,5,10,2/15 p,4/15 p,2/15 p,1/15 p,0/15 p,None,<5,5,<5,<5,80.0,25,95.0,95.0,95.0,95.0,5,5.0,None,NaN,None,<5,20,NaN,<5,No logrado,NaN,NaN,None,None,None,None,M,1
1,95,95,95,14,60,9,11,95.0,95,95,6/16 p,9/16 p,4/16 p,5/16 p,8/16 p,None,15/16 p,75,None,None,95.0,85,95.0,95.0,NaN,NaN,12,11.0,None,NaN,None,None,70,13.0,70,85,NaN,NaN,25,45,None,35,F,0
2,95,95,95,6,<5,7,6,95.0,95,95,2/16 p,5/16 p,2/16 p,2/16 p,3/16 p,None,15/16 p,5,None,None,95.0,<5,95.0,95.0,95.0,95.0,4,6.0,None,NaN,None,<5,95,NaN,<5,<5,NaN,NaN,<5,<5,None,<5,M,1
3,95,95,95,8,<5,5,4,95.0,5,95,2/16 p,9/16 p,4/16 p,7/16 p,6/16 p,None,8/16 p,40,None,None,95.0,15,95.0,95.0,95.0,95.0,7,5.0,None,NaN,None,10,5,NaN,20,<5,NaN,NaN,5,<5,None,<5,F,1
4,95,95,95,10,50,9,9,95.0,95,20,6/16 p,13/16 p,6/16 p,10/16 p,8/16 p,None,14/16 p,75,None,None,95.0,85,95.0,95.0,95.0,95.0,12,NaN,>95,75.0,80,>95,40,11.0,90,85,90.0,85.0,55,None,None,None,F,0
5,95,95,95,11,<20,11,5,95.0,95,10,1/16 p,9/16 p,4/16 p,7/16 p,6/16 p,None,11/16 p,5,None,None,95.0,55,95.0,95.0,95.0,95.0,7,NaN,55,40.0,25,30,90,NaN,95,45,5.0,15.0,15,None,None,None,F,1
6,95,95,5,8,95,13,11,95.0,95,95,3/16 p,7/16 p,2/16 p,6/16 p,6/16 p,None,12/16 p,95,None,None,95.0,85,NaN,NaN,95.0,95.0,10,10.0,25,55.0,25,None,60,11.0,95,65,NaN,NaN,45,30,None,30,M,0
7,95,95,95,8,95,10,10,95.0,<5,95,4/15 p,10/15 p,4/15 p,7/15 p,8/15 p,None,14/15 p,35,None,None,95.0,70,NaN,NaN,95.0,95.0,9,6.0,20,20.0,20,None,60,7.0,60,55,NaN,NaN,35,45,None,20,F,0
8,95,95,95,11,80,11,10,95.0,95,95,6/16 p,15/16 p,7/16 p,14/16 p,14/16 p,None,15/16 p,75,None,None,95.0,85,NaN,NaN,NaN,NaN,12,14.0,60,75.0,90,90,None,13.0,95,95,NaN,NaN,55,30,None,45,F,0
9,95,95,95,10,95,9,12,95.0,95,95,7/16 p,14/16 p,7/16 p,13/16 p,15/16 p,None,16/16 p,>95,None,None,95.0,85,NaN,NaN,NaN,NaN,10,14.0,20,65.0,<5,25,70,11.0,95,90,NaN,NaN,75,60,None,75,M,0
10,95,95,95,8,60,10,10,NaN,<5,95,3/15 p,10/15 p,2/15 p,0/15 p,3/15 p,None,14/15 p,35,None,None,NaN,55,NaN,NaN,NaN,NaN,7,9.0,None,NaN,None,None,<5,1.0,<5,<5,NaN,NaN,10,45,None,10,M,2

## DC

In [49]:
url = "https://raw.githubusercontent.com/Nicolasg2c/dc_model_ts/main/common/data/datos_deterioro_cognitivo.xlsx"

headers = {"Authorization": f"Bearer {config['GITHUB_TOKEN']}"}
r = requests.get(url, headers=headers, timeout=30)
r.raise_for_status()  # Check if the request was successful

xlsx_data = pd.read_excel(BytesIO(r.content), header=None, sheet_name=None, engine="openpyxl")

In [58]:
cleaned_sheets_dc = {}
for name, sheet in xlsx_data.items():
    sheet = sheet.dropna(how="all")       # eliminar filas vacías
    sheet.columns = sheet.iloc[0]         # primera fila como headers
    sheet = sheet.drop(sheet.index[0])    # eliminar fila usada como header
    sheet = sheet.reset_index(drop=True)
    cleaned_sheets_dc[name] = sheet
    
dc_data = []
for i, patient in enumerate(cleaned_sheets_dc):
  print(patient)
  try:
    patient_data = search_values(cleaned_sheets_dc[patient], test, i)
    # patient_data['sexo'] = 'M' if 'H' in patient else 'F'
    patient_data['dc'] = 0 if 'F06' in patient else 1 if 'F02' in patient else 2
    patient_data['sheet_name'] = patient
    dc_data.append(patient_data)
  except Exception as e:
    print(f'ocurrio un error {e}')

S1-F067-58
ocurrio un error 'float' object has no attribute 'strip'
GC1-60
GC2-62
F021-72
S2-F067-53
GC3-60
S3-F067-66
GC4-72
GC5-62
S4-F067-66
GC6-69
GC7-70
F022-71
GC8-79
ocurrio un error 'float' object has no attribute 'strip'
S5-F067-73
ocurrio un error 'float' object has no attribute 'strip'
F023-87
ocurrio un error 'float' object has no attribute 'strip'
F024-72
ocurrio un error 'float' object has no attribute 'strip'
S6-F067-65
ocurrio un error 'float' object has no attribute 'strip'
F025-82
ocurrio un error 'float' object has no attribute 'strip'
GC8-80
ocurrio un error 'float' object has no attribute 'strip'
GC9-66
ocurrio un error 'float' object has no attribute 'strip'
GC10-65
ocurrio un error 'float' object has no attribute 'strip'
F026-92
ocurrio un error 'float' object has no attribute 'strip'
S7-F067-76
ocurrio un error 'float' object has no attribute 'strip'
S8-F067-75
ocurrio un error 'float' object has no attribute 'strip'
F027-79
ocurrio un error 'float' object has no attribute 'strip'
CG11-72
ocurrio un error 'float' object has no attribute 'strip'
S9-F067-66
ocurrio un error 'float' object has no attribute 'strip'
S10-F067-65
ocurrio un error 'float' object has no attribute 'strip'
GC12-65
ocurrio un error 'float' object has no attribute 'strip'
S11-F067-84
ocurrio un error 'float' object has no attribute 'strip'
F028-70
ocurrio un error 'float' object has no attribute 'strip'
s12-f067-77
ocurrio un error 'float' object has no attribute 'strip'
S13-F067-77
ocurrio un error 'float' object has no attribute 'strip'
F029-62
ocurrio un error 'float' object has no attribute 'strip'
S14-F067-69
ocurrio un error 'float' object has no attribute 'strip'
F0210-77
ocurrio un error 'float' object has no attribute 'strip'
F0211-79
ocurrio un error 'float' object has no attribute 'strip'
S15-F067-74
ocurrio un error 'float' object has no attribute 'strip'
F0212-65
ocurrio un error 'float' object has no attribute 'strip'
GC13-74
ocurrio un error 'numpy.float64' object has no attribute 'strip'
S16-F067-60
ocurrio un error 'numpy.float64' object has no attribute 'strip'
GC14-67
ocurrio un error 'numpy.float64' object has no attribute 'strip'
F0213-85
ocurrio un error 'float' object has no attribute 'strip'
S17-F067-76
ocurrio un error 'float' object has no attribute 'strip'
S18-F067-72
ocurrio un error 'float' object has no attribute 'strip'
F0214-73
ocurrio un error 'float' object has no attribute 'strip'
S19-F064-74
ocurrio un error 'float' object has no attribute 'strip'
S20-F067-57
ocurrio un error 'float' object has no attribute 'strip'
S21-F067-68
ocurrio un error 'float' object has no attribute 'strip'
S22-F067-86
ocurrio un error 'float' object has no attribute 'strip'
GC15-64
ocurrio un error 'float' object has no attribute 'strip'
S23-F067-66
ocurrio un error 'float' object has no attribute 'strip'
S24-F067-96
ocurrio un error 'float' object has no attribute 'strip'
GC16-76
ocurrio un error 'float' object has no attribute 'strip'
F0215-73
ocurrio un error 'float' object has no attribute 'strip'
S25-F067-80
ocurrio un error 'float' object has no attribute 'strip'
F0216-83
ocurrio un error 'float' object has no attribute 'strip'
F0217-88
ocurrio un error 'float' object has no attribute 'strip'
F0218-77
ocurrio un error 'float' object has no attribute 'strip'
S26-F067-81
ocurrio un error 'float' object has no attribute 'strip'
S27-F067-66
ocurrio un error 'float' object has no attribute 'strip'
S28-F067-65
ocurrio un error 'float' object has no attribute 'strip'
S29-F067-82
ocurrio un error 'float' object has no attribute 'strip'
F0219-74
ocurrio un error 'float' object has no attribute 'strip'
S30-F067-87
ocurrio un error 'float' object has no attribute 'strip'
S31-F067-83
ocurrio un error 'float' object has no attribute 'strip'
S32-F067-60
ocurrio un error 'float' object has no attribute 'strip'
S33-F067-57
F0220-77
ocurrio un error 'float' object has no attribute 'strip'
F0221-57
ocurrio un error 'float' object has no attribute 'strip'
S34-F067-71
ocurrio un error 'numpy.float64' object has no attribute 'strip'
F0222-64
ocurrio un error 'numpy.float64' object has no attribute 'strip'
S35-F067-67
ocurrio un error 'numpy.float64' object has no attribute 'strip'
GC17-60
ocurrio un error 'numpy.float64' object has no attribute 'strip'
S36-F067-51
ocurrio un error 'numpy.float64' object has no attribute 'strip'
F0223-73
ocurrio un error 'numpy.float64' object has no attribute 'strip'
GC18-52
ocurrio un error 'float' object has no attribute 'strip'
S37-F067-81
ocurrio un error 'float' object has no attribute 'strip'
F0224-81
ocurrio un error 'float' object has no attribute 'strip'
F0225-84
ocurrio un error 'float' object has no attribute 'strip'
S38-F067-74
ocurrio un error 'float' object has no attribute 'strip'
S39-F067-74
ocurrio un error 'float' object has no attribute 'strip'
S40-F067-78
ocurrio un error 'float' object has no attribute 'strip'
S41-F067-76
ocurrio un error 'float' object has no attribute 'strip'
GC19-53
ocurrio un error 'float' object has no attribute 'strip'
F0226-70
ocurrio un error 'float' object has no attribute 'strip'
F0227-78
ocurrio un error 'float' object has no attribute 'strip'
S42-F067-68
ocurrio un error 'float' object has no attribute 'strip'
S43-F067-80
ocurrio un error 'float' object has no attribute 'strip'
S44-F067-69
ocurrio un error 'float' object has no attribute 'strip'
F0228-86
ocurrio un error 'float' object has no attribute 'strip'
S45-F067-57
ocurrio un error 'float' object has no attribute 'strip'
GC20-59
ocurrio un error 'numpy.float64' object has no attribute 'strip'
S46-F067-66
ocurrio un error 'numpy.float64' object has no attribute 'strip'
GC21-64
ocurrio un error 'numpy.float64' object has no attribute 'strip'
S47-F067-64
ocurrio un error 'float' object has no attribute 'strip'
S48-F067-61
ocurrio un error 'numpy.float64' object has no attribute 'strip'
S49-F067-60
ocurrio un error 'numpy.float64' object has no attribute 'strip'
GC22-53
ocurrio un error 'numpy.float64' object has no attribute 'strip'
GC23-61
ocurrio un error 'numpy.float64' object has no attribute 'strip'
GC24-52
S50-F067-55
GC25-61
S51-F067-73
S52-F067-78
S53-F067-54
S54-F067-68
S55-F067-64
GC26-59
F0229-71
F0230-67
ocurrio un error 'float' object has no attribute 'strip'
S56-F067-73
S57-F067-55
GC27-55
GC28-59
F0231-71
ocurrio un error 'float' object has no attribute 'strip'
F0232-81
ocurrio un error 'float' object has no attribute 'strip'
S58-F067-65
ocurrio un error 'float' object has no attribute 'strip'
S59-F067-84
ocurrio un error 'float' object has no attribute 'strip'
S60-F067-72
ocurrio un error 'float' object has no attribute 'strip'
S61-F067-75
ocurrio un error 'float' object has no attribute 'strip'
F0233-85
ocurrio un error 'float' object has no attribute 'strip'
GC29-65
ocurrio un error 'float' object has no attribute 'strip'
F0234-87
ocurrio un error 'float' object has no attribute 'strip'

In [59]:
dc_df = pd.DataFrame(dc_data)
dc_df

,orientacion_en_persona,orientacion_en_espacio,orientacion_en_tiempo,atencion_sostenida_auditiva,atencion_sostenida_visual,atencion_selectiva_visual,atencion_dividida_visual,denominacion_de_imagenes,comprension_de_ordenes,material_verbal_complejo,evocacion_inmediata_lista_a,recuerdo_inmediato_lista_a,recuerdo_inmediato_lista_b,recuerdo_libre_a_corto_plazo,recuerdo_libre_a_largo_plazo,recuerdo_libre_a_largo_plazo_clave,reconocimiento,evocacion_diferida,reconocimiento_inmediato_ensayo_2,reconocimiento_diferido_ensayo_3,imagenes_superpuesta,constructiva,ideomotora_gestos_simbolicos_a_la_orden_derecha,ideomotora_gestos_simbolicos_a_la_orden_izquierda,ideomotora_gestos_simbolicos_a_la_imitacion_derecha,ideomotora_gestos_simbolicos_a_la_imitacion_izquierda,memoria_de_trabajo_digitos_inversos,memoria_de_trabajo_digitos_secuenciales,test_de_fluidez_fonologica_fas_f,test_de_fluidez_fonologica_fas_a,test_de_fluidez_fonologica_fas_s,evocacion_categorial_semantica,semejanzas,matrices,comprension_abstraccion,atencion_alternante,stroop_a,stroop_b,stroop_c,stroop_palabra,stroop_colores,stroop_interferencia,dc,sheet_name
0,NaN,NaN,NaN,6,NaN,9,8,95.0,95,30.0,3/16 p,7/16 p,6/16 p,7/16 p,6/16 p,None,12/16 p,NaN,None,None,95.0,NaN,95,None,None,None,7,6.0,None,None,None,NaN,10,8.0,95,NaN,NaN,NaN,NaN,NaN,None,NaN,2,GC1-60
1,95.0,95.0,95,14,60,9,11,95.0,95,95.0,6/16 p,9/16 p,4/16 p,5/16 p,8/16 p,None,15/16 p,75,None,None,95.0,85,95,95,None,None,12,11.0,None,None,None,None,70,13.0,70,85,NaN,NaN,25,45,None,35,2,GC2-62
2,95.0,95.0,95,6,<5,7,6,95.0,95,95.0,2/16 p,5/16 p,2/16 p,2/16 p,3/16 p,None,15/16 p,5,None,None,95.0,<5,95,95,95,95,4,6.0,None,None,None,<5,95,NaN,<5,<5,NaN,NaN,<5,<5,None,<5,1,F021-72
3,95.0,95.0,95,8,<5,5,4,95.0,5,95.0,2/16 p,9/16 p,4/16 p,7/16 p,6/16 p,None,8/16 p,40,None,None,95.0,15,95,95,95,95,7,5.0,None,None,None,10,5,NaN,20,<5,NaN,NaN,5,<5,None,<5,0,S2-F067-53
4,95.0,95.0,95,10,50,9,9,95.0,95,20.0,6/16 p,13/16 p,6/16 p,10/16 p,8/16 p,None,14/16 p,75,None,None,95.0,85,95,95,95,95,12,NaN,>95,75,80,>95,40,11.0,90,85,90.0,85.0,55,None,None,None,2,GC3-60
5,95.0,95.0,95,11,<20,11,5,95.0,95,10.0,1/16 p,9/16 p,4/16 p,7/16 p,6/16 p,None,11/16 p,5,None,None,95.0,55,95,95,95,95,7,NaN,55,40,25,30,90,NaN,95,45,5.0,15.0,15,None,None,None,0,S3-F067-66
6,95.0,95.0,5,8,95,13,11,95.0,95,95.0,3/16 p,7/16 p,2/16 p,6/16 p,6/16 p,None,12/16 p,95,None,None,95.0,85,None,None,95,95,10,10.0,25,55,25,None,60,11.0,95,65,NaN,NaN,45,30,None,30,2,GC4-72
7,95.0,95.0,95,8,95,10,10,95.0,<5,95.0,4/15 p,10/15 p,4/15 p,7/15 p,8/15 p,None,14/15 p,35,None,None,95.0,70,None,None,95,95,9,6.0,20,20,20,None,60,7.0,60,55,NaN,NaN,35,45,None,20,2,GC5-62
8,95.0,95.0,95,9,55,11,10,95.0,95,95.0,4/16 p,9/16 p,3/16 p,6/16 p,8/16 p,None,14/16 p,NaN,None,None,NaN,75,None,None,95,95,9,10.0,None,None,None,None,95,NaN,95,65,NaN,NaN,35,10,None,15,0,S4-F067-66
9,95.0,95.0,95,11,80,11,10,95.0,95,95.0,6/16 p,15/16 p,7/16 p,14/16 p,14/16 p,None,15/16 p,75,None,None,95.0,85,None,None,None,None,12,14.0,60,75,90,90,None,13.0,95,95,NaN,NaN,55,30,None,45,2,GC6-69
10,95.0,95.0,95,10,95,9,12,95.0,95,95.0,7/16 p,14/16 p,7/16 p,13/16 p,15/16 p,None,16/16 p,>95,None,None,95.0,85,None,None,None,None,10,14.0,20,65,<5,25,70,11.0,95,90,NaN,NaN,75,60,None,75,2,GC7-70
11,95.0,95.0,95,8,60,10,10,NaN,<5,95.0,3/15 p,10/15 p,2/15 p,0/15 p,3/15 p,None,14/15 p,35,None,None,NaN,55,None,None,None,None,7,9.0,None,None,None,None,<5,1.0,<5,<5,NaN,NaN,10,45,None,10,1,F022-71
12,NaN,NaN,None,10,35,5,8,95.0,None,NaN,5/15 p,7/15 p,5/15 p,5/15 p,4/15 p,None,7/15 p,10,None,None,NaN,40,None,None,None,None,10,9.0,None,None,None,None,None,7.0,80,25,NaN,NaN,None,20,None,None,0,S33-F067-57
13,95.0,95.0,>5,6,75,5,6,95.0,>5,95.0,4/16 p,6/16 p,5/16 p,4/16 p,4/16 p,None,5/16 p,35,None,None,95.0,85,None,95,95,95,5,5.0,None,None,None,None,30,6.0,10,35,NaN,NaN,15,20,None,20,2,GC24-52
14,95.0,95.0,95,9,85,10,10,95.0,95,95.0,4/16 p,7/16 p,5/16 p,7/16 p,7/16 p,None,11/16 p,40,None,None,95.0,45,None,95,95,95,6,6.0,None,None,None,None,50,8.0,95,95,NaN,NaN,75,60,None,45,0,S50-F067-55
15,95.0,95.0,95,19,>95,13,15,95.0,95,95.0,5/16 p,13/16 p,8/16 p,11/16 p,8/16 p,None,15/16 p,>95,None,None,95.0,85,None,None,None,None,14,14.0,None,None,None,None,95,13.0,95,>95,NaN,NaN,75,65,None,85,2,GC25-61
16,95.0,95.0,95,12,65,9,10,95.0,5,40.0,3/15 p,5/15 p,1/15 p,0/15 p,0/15 p,None,6/15 p,<5,None,None,95.0,60,None,None,None,None,10,11.0,55,70,80,None,95,10.0,70,70,NaN,NaN,45,35,None,45,0,S51-F067-73
17,95.0,95.0,95,9,<20,5,4,95.0,<5,95.0,4/16 p,7/16 p,3/16 p,0/16 p,3/16 p,None,11/16 p,20,None,None,10.0,5,<5,<5,<5,<5,9,9.0,<5,<5,15,55,80,8.0,70,No logrado,NaN,NaN,None,None,None,None,0,S52-F067-78
18,95.0,95.0,95,3,45,5,5,NaN,95,95.0,1/15 p,6/15 p,3/15 p,2/15 p,3/15 p,None,10/15 p,45,None,None,NaN,70,None,None,None,None,5,5.0,None,None,None,5,4,5.0,<5,<5,NaN,NaN,None,None,None,None,0,S53-F067-54
19,95.0,95.0,95,11,30,7,6,NaN,95,95.0,3/15 p,5/15 p,0/15 p,2/15 p,0/15 p,None,5/15 p,<5,None,None,95.0,85,None,None,None,None,15,10.0,None,None,None,20,<5,8.0,60,<5,45.0,10.0,<5,None,None,None,0,S54-F067-68
20,95.0,95.0,95,9,<5,9,7,NaN,95,95.0,5/16 p,9/16 p,5/16 p,7/16 p,7/16 p,None,12/16 p,30,None,None,95.0,55,None,None,None,None,12,10.0,None,None,None,80,95,9.0,95,<5,10.0,35.0,10,None,None,None,0,S55-F067-64
21,95.0,95.0,95,8,90,9,9,NaN,95,95.0,7/16 p,15/16 p,5/16 p,10/16 p,7/16 p,None,16/16 p,30,None,None,95.0,45,None,None,None,None,7,7.0,None,None,None,80,70,7.0,95,75,40.0,50.0,35,None,None,None,2,GC26-59
22,95.0,95.0,<5,12,45,6,10,95.0,<5,95.0,2/16 p,6/16 p,2/16 p,1/16 p,0/16 p,None,13/16 p,<5,None,None,95.0,85,95,95,95,95,12,8.0,None,None,None,80,30,8.0,10,40,45.0,30.0,30,None,None,None,1,F0229-71
23,95.0,95.0,95,15,45,12,9,95.0,95,95.0,3/15 p,10/15 p,3/15 p,6/15 p,8/15 p,None,14/15 p,10,None,None,95.0,<5,95,None,None,None,12,13.0,None,None,None,None,50,NaN,95,15,NaN,NaN,30,45,None,40,0,S56-F067-73
24,95.0,95.0,95,8,45,6,6,95.0,95,95.0,2/15 p,7/15 p,2/15 p,5/15 p,5/15 p,None,12/15 p,25,None,None,NaN,75,None,None,None,None,6,6.0,None,None,None,None,<5,NaN,<5,<15,NaN,NaN,10,10,None,15,0,S57-F067-55
25,NaN,NaN,None,10,>95,13,14,NaN,None,NaN,4/16 p,16/16 p,6/16 p,11/16 p,6/16 p,None,13/16 p,30,None,None,95.0,85,None,None,None,None,12,16.0,None,None,None,None,20,11.0,95,>95,NaN,NaN,75,45,None,90,2,GC27-55
26,NaN,NaN,None,12,85,9,8,NaN,None,NaN,4/15 p,12/15 p,3/15 p,11/15 p,11/15 p,None,15/15 p,25,None,None,95.0,80,None,None,None,None,11,10.0,None,None,None,None,30,9.0,95,<5,NaN,NaN,65,60,None,55,2,GC28-59